<?php
// $Id$

/**
 * This module generates images to update the chumby
 *
 * Copyright (c) 2010 Fraunhofer Institut ITWM (www.itwm.fraunhofer.de)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

function chumby_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#chumby":
      $output = '<p>'.t("This module provides personalized images to update the chumby.").'</p>';
      break;
  }
  return $output;
} //chumby_help

function chumby_perm() {
  return array('chumby image');
}

function chumby_settings_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}

function chumby_menu() {
  
  $item = array();

  $items['chumby'] = array(
    'title'            => "Download chumby image",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('chumby_form'),
    'access arguments' => array('chumby image'),
    'type'             => MENU_NORMAL_ITEM,
  );

  return $items;
}

function chumby_cron() {
  exec('rm ' . drupal_get_path('module', 'chumby') . '/files/*.zip');
}

function chumby_form() {
  global $user;
  $result = db_query('SELECT meter, function FROM {logger_meters} WHERE uid=%d AND function IS NOT NULL', $user->uid);
  $sensors = array();
  while($flukso = db_fetch_object($result)) {
    $sensors[$flukso->meter] = $flukso->function;
  }
  $result = array();
  $result['visualization'] = array(
    '#type' => 'checkboxes',
    '#options' => array(
       'text' => t('currentpower'),
       'tacho' => t('energietacho'),
       'lightbulb' => t('Gluehlampe'),
       'graph' => t('EnergyGraph'),
      ),
    '#title' => t('Visualizations'),
    '#description' => t('Visualizations that should be available'),
    );
  $result['sensor'] = array(
    '#type' => 'select',
    '#options' => $sensors,
    '#title' => t('Sensor'),
    '#description' => t('Sensors from which values should be displayed.'),
  );
  $result['auto'] = array(
    '#type' => 'checkbox',
    '#title' => t('Autoconfigure IP'),
    '#description' => t('Automatically find the flukso in the local network. Normally this is the way you want to go.'),
    '#default_value' => '1',
    '#attributes' => array('onChange' => 'document.getElementById("edit-ip").disabled = document.getElementById("edit-auto").checked'),
  );
  $result['ip'] = array(
    '#type' => 'textfield',
    '#title' => t('ip address'),
    '#description' => t('The local ip address of the flukso.'),
    '#disabled' => true,
  );
  $result['consumption'] = array(
    '#type' => 'fieldset',
    '#title' => t('consumption'),
    '#description' => t('average borders for high, normal and low energy consumption in Watt'),
    '#collapsable' => TRUE,
    '#collapsed' => FALSE,
  );
  $result['consumption']['low'] = array(
    '#type' => 'textfield',
    '#title' => t('low'),
    '#default_value' => '200',
  );
  $result['consumption']['normal'] = array(
    '#type' => 'textfield',
    '#title' => t('normal'),
    '#default_value' => '500',
  );
  $result['consumption']['high'] = array(
    '#type' => 'textfield',
    '#title' => t('high'),
    '#default_value' => '1500',
  );
  $result['submit'] = array(
    '#type' => 'submit',
    '#value' => t("Submit"),
  );
  return $result;
}

function theme_chumby_form($form) {
  $header = array('', '', '');
  $output = theme('table', $header, $form['visualization']);
  return $output;
}

function chumby_form_validate($form, &$form_state) {
  // check if any visualization is selected.
  $temp = TRUE;
  foreach ( $form_state['values']['visualization'] as $value )
    $temp &= ($value == '0');
  if ( $temp )
    form_set_error('visualization', t('Please choose at least one visualization.'));

  if ( !$form_state['values']['auto'] ) {
    // check if a valid ip address was entered.
    if ( filter_var($form_state['values']['ip'], FILTER_VALIDATE_IP) == FALSE )
      form_set_error('ip', t('Please enter a valid IP address.'));
  };

  // check if a valid number was entered as low value.
  if ( $form_state['values']['low'] == "" || filter_var($form_state['values']['low']) == FALSE )
    form_set_error('low', t('Please enter a number value.'));

  // check if a valid number was entered as normal value and if the normal value is larger than the low value.
  if ( $form_state['values']['normal'] == "" || filter_var($form_state['values']['normal']) == FALSE )
    form_set_error('normal', t('Please enter a number value.'));
  else if ( $form_state['values']['normal'] < $form_state['values']['low'] )
    form_set_error('normal', t('The normal value should be higher than the low value.'));

  // check if a valid number was entered as high value and if the high value is larger than the normal value.
  if ( $form_state['values']['high'] == "" || filter_var($form_state['values']['high']) == FALSE )
    form_set_error('high', t('Please enter a number value.'));
  else if ( $form_state['values']['high'] < $form_state['values']['normal'] )
    form_set_error('normal', t('The high value should be higher than the normal value.'));
}

function chumby_form_submit($form, &$form_state) {
  if ( $form_state['values']['auto'] )
    $ip = "";
  else
    $ip = $form_state['values']['ip'];
  $sensor = $form_state['values']['sensor'];
  $token = db_result(db_query("SELECT token FROM {logger_tokens} WHERE meter='%s'", $sensor));
  $low = $form_state['values']['low'];
  $mid = $form_state['values']['normal'];
  $high = $form_state['values']['high'];
  require('daemonconfig.php');
  $rootpath = '/tmp/chumby/';
  if ( ! file_exists($rootpath) )
    mkdir($rootpath);
  $dirname = md5(uniqid(rand(), TRUE));
  $path = $rootpath . $dirname;
  if ( ! file_exists($path) ) {
    mkdir($path);
    exec("cp -R " . drupal_get_path('module', 'chumby') . "/template/usr/ " . $path);
    exec("cp -R " . drupal_get_path('module', 'chumby') . "/template/debugchumby " . $path);
    $daemonconfig = fopen($path . '/daemonconfig.lua', 'w');
    if ( $daemonconfig == FALSE )
     drupal_set_message(t('Could not create file!'));
    else {
      fwrite($daemonconfig, $config);
      fclose($daemonconfig);
      $profile = fopen($path . '/profile.xml', 'w');
      require('profile-head.php');
      fwrite($profile, $profile_head);
      foreach ($form_state['values']['visualization'] as $key => $value) {
        if ( $value != '0' ) {
          require($key . '_widget.php');
          fwrite($profile, $widget);
        }
      }
      require('profile-tail.php');
      fwrite($profile, $profile_tail);
      fclose($profile);
    }
    $file_path = drupal_get_path('module', 'chumby') . '/files/';
    if ( ! file_exists($file_path) )
      mkdir($file_path);
    $zipfile = $file_path . $dirname . '.zip';
    exec('pushd ' . $path .'; zip -r ' . $dirname . '.zip .; popd; cp ' . $path . '/' . $dirname . '.zip ' . $zipfile);
    drupal_set_message('<a href="' . drupal_get_path('module', 'chumby') . '/files/' . $dirname . '.zip">' . t('Download Image') . '</a>');
    exec("rm -rf " . $rootpath . $dirname);
  } else {
    drupal_set_message(t("Operation failed! Please try again later!"));
  }
}
