<?php
// $Id$

function notification_node_info() {
  return array(
    'notification' => array(
      'name' => t('Notification'),
      'module' => 'notification',
      'description' => t('Event Notification'),
      'has_title' => FALSE,
      'has_body' => FALSE,
      'locked' => TRUE
    )
  );
}

function notification_perm() {
  return array('manage notifications');
}

function notification_menu() {

  $items = array();

  $items['notification_list'] = array(
    'title' => 'Event Notifications',
    'page callback' => 'notification_list_page',
    'access arguments' => array('notification'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['notification_delete'] = array(
    'title' => $items['notification_list']['title'],
    'page callback' => 'notification_delete',
    'page arguments' => array(1, 2),
    'access arguments' => array('notification'),
    'type' => MENU_CALLBACK
  );

  $items['notification_register'] = array(
    'title' => 'Event Notification Registration',
    'page callback' => 'notification_register_page',
    'access arguments' => array('notification'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function notification_settings_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}

function notification_register_page() {
  $output .= drupal_get_form('notification_register_form');
  return $output;
}

function notification_list_page() {

  $sql = "
    SELECT
      d.serial AS serial,
      e.name AS event_name,
      n.email AS email,
      n.limit_up AS limit_up,
      d.device AS device,
      e.id AS event_id
    FROM
      {logger_devices} d,
      {notification} n,
      {event} e
    WHERE
      d.uid = %d AND
      d.device = n.device AND
      n.event_id = e.id";

  $header = array(
    array('data' => t('Device'), 'field' => 'serial', 'sort' => 'ASC'),
    array('data' => t('Event'), 'field' => 'event_name', 'sort' => 'ASC'),
    array('data' => t('Target e-mail'), 'field' => 'email')
  );

  global $user;
  $result = db_query($sql, $user->uid, tablesort_sql($header));

  $rows = array();
  while ($object = db_fetch_array($result)) {

    $row = array();
    $row['serial'] = $object['serial'];
    $row['event_name'] = _notification_format_event_name($object['event_id'], $object['event_name'], $object['limit_up']);
    $row['email'] = $object['email'];
    $row[] = l('Remove', 'notification_delete/' . $object['device'] . '/' . $object['event_id']);

    $rows[] = $row;
  }

  $caption = '<p>' . l(t('Register Notification'), 'notification_register') . '</p>';

  $output .= theme('table', $header, $rows, array(), $caption);
  return $output;
}

function _notification_format_event_name($event_id, $event_name, $limit_up) {

  $name;	
  if ($event_id == 1 || $event_id == 3) {
    $name = "%event_name (in %limit_up min)";

  } else if ($event_id == 4) {
    $name = "%event_name (%limit_up watts)";

  } else {
    $name = "%event_name";
  }
  return t($name, array('%event_name' => $event_name, '%limit_up' => $limit_up));
}

function _notification_get_devices_options() {
  
  $sql = "SELECT serial, device FROM {logger_devices} WHERE uid = %d ORDER BY serial";

  global $user;
  $result = db_query($sql, $user->uid);

  $devices = array();
  while ($row = db_fetch_array($result)) {
    $devices[$row['device']] = $row['serial'];
  }

  return $devices;    
}	

function _notification_get_events_options() {

  $sql = "SELECT id, name FROM {event} ORDER BY id";
  $result = db_query($sql);

  $events = array();
  while ($row = db_fetch_array($result)) {
    $events[$row['id']] = t($row['name']);
  }  

  return $events;
}

function notification_register_form() {

  global $user;

  $form['email'] = array(
    '#type' => 'textfield',
    '#description' => t('Enter the e-mail to which the notification will be sent.'),
    '#maxlength' => 64,
    '#size' => 20,
    '#default_value' => $user->mail
  );

  $form['device'] = array(
    '#type' => 'select',
    '#description' => t('Select the serial number of the monitored device.'),
    '#options' => _notification_get_devices_options()
  );

  $form['event_id'] = array(
    '#type' => 'select',
    '#description' => t('Select the event to be detected and notified.'),
    '#options' => _notification_get_events_options(),
    '#default_value' => 1,
    '#attributes' => array(
      'onchange' => '
      wrapper = document.getElementById("edit-limit-up-wrapper");
      wrapper.style.visibility = (this.value == 2? "hidden" : "visible");'
    )
  );

  $form['limit_up'] = array(
    '#type' => 'textfield',
    '#description' => t('For "Peak Consumption", enter the maximum eletricity consumption in watts. Otherwise, enter the maximum heartbeat delay in minutes. Beyond these limits, the device is considered faulty.'),
    '#maxlength' => 6,
    '#size' => 6,
    '#default_value' => 120
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  
  return $form;
}

function notification_register_form_submit($form, &$form_state) {

  $device = $form_state['values']['device'];
  $event_id = $form_state['values']['event_id'];
  $email = $form_state['values']['email'];
  $limit_up = $form_state['values']['limit_up'];

  _notification_delete($device, $event_id);
  _notification_insert($device, $event_id, $email, $limit_up);

  $form_state['redirect'] = 'notification_list';
}

function notification_register_form_validate($form, &$form_state) {

  $email = $form_state['values']['email'];
  $event_id = $form_state['values']['event_id'];
  $limit_up = $form_state['values']['limit_up'];

  if (!valid_email_address($email)) {
    form_set_error('email', t('Invalid e-mail.'));
  }

  if(($event_id == 1 || $event_id == 3) && $limit_up < 30) {
    form_set_error('limit_up', t('Delay time can not be less than 30 minutes.'));

  } else if ($event_id == 4 && $limit_up < 1) {
    form_set_error('limit_up', t('Peak consumption can not be less than 1 watt.'));
  }
}

function notification_delete($device, $event_id) {

  _notification_delete($device, $event_id);
  return notification_list_page();
}

function _notification_delete($device, $event_id) {

  $sql = "DELETE FROM {notification} WHERE device = '%s' AND event_id = %d";
  db_query($sql, $device, $event_id);
}

function _notification_insert($device, $event_id, $email, $limit_up) {
      
  $sql = "INSERT INTO {notification} (device, event_id, email, limit_up) VALUES('%s', %d, '%s', %d)";
  db_query($sql, $device, $event_id, $email, $limit_up);
}

function notification_cron() {

  _notification_send_no_heartbeat_emails();
  _notification_send_corrupted_heartbeat_emails();
  _notification_send_any_heartbeat_failure_emails();
  _notification_send_peak_consumption_emails();
}

function _notification_send_emails($message, $sql) {

  $result = db_query($sql);

  while ($object = db_fetch_array($result)) {

    $variables = array();
    foreach ($object as $key => $value) {
      $variables["%$key"] = $value;
    }

    $body = t($message, $variables);

    $params = array(
      'subject' => t('Event Notification'),
      'body' => $body
    );

    drupal_mail('notification', 'notice', $object['email'], language_default(), $params);
  }
}

function _notification_send_no_heartbeat_emails($event_id = 1) {

  $sql = "
    SELECT
      u.name AS user_name,
      n.email AS email,       
      d.serial AS serial,
      FROM_UNIXTIME(d.access) AS event_time,
      n.limit_up AS limit_up
    FROM
      {logger_devices} d,
      {users} u,
      {notification} n
    WHERE
      SYSDATE() > (FROM_UNIXTIME(d.access) + INTERVAL n.limit_up MINUTE) AND
      n.device = d.device AND
      n.event_id = $event_id AND
      d.uid = u.uid";

  $message = "
    <p>Dear user %user_name</p>
    <p>Your Flukso device <b>%serial</b> has not been sending heartbeats for %limit_up minutes, since <b>%event_time</b>.
    Please, check your WLAN and Flukso installations.</p>
    <p>Best Regards,</p>
    <p>mySmartGrid System</p>";

  _notification_send_emails($message, $sql);
}

function _notification_send_corrupted_heartbeat_emails($event_id = 2) {

  $sql = "
    SELECT
      u.name AS user_name,
      n.email AS email,
      d.serial AS serial,
      FROM_UNIXTIME(d.access) AS event_time
    FROM
      {logger_meters} m,
      {logger_devices} d,
      {users} u,
      {notification} n
    WHERE
      TIMEDIFF(FROM_UNIXTIME(d.access), FROM_UNIXTIME(m.access)) > TIME('00:10:00') AND
      n.device = d.device AND
      n.event_id = $event_id AND
      d.uid = u.uid AND
      d.device = m.device AND
      m.type = 'electricity'";

  $message = "
    <p>Dear user %user</p>
    <p>Your Flukso device <b>%serial</b> has sent a heartbeat with corrupted data at <b>%event_time</b>.
    Please, check your WLAN and Flukso installations.</p>
    <p>Best Regards,</p>
    <p>mySmartGrid System</p>";

  _notification_send_emails($message, $sql);
}

function _notification_send_any_heartbeat_failure_emails() {

  _notification_send_no_heartbeat_emails(3);
  _notification_send_corrupted_heartbeat_emails(3);
}

function _notification_send_peak_consumption_emails() {

  $sql = "
    SELECT
      u.name AS user_name,
      n.email AS email,
      d.serial AS serial,
      FROM_UNIXTIME(d.access) AS event_time,
      n.limit_up AS limit_up
    FROM
      {logger_meters} m,
      {logger_devices} d,
      {users} u,
      {notification} n
    WHERE
      m.value > n.limit_up AND
      m.type = 'electricity' AND
      m.unit = 'watt' AND
      n.device = d.device AND
      d.device = m.device AND
      n.event_id = 4 AND
      d.uid = u.uid";

  $message = "
    <p>Dear user %user_name</p>
    <p>Your Flukso device <b>%serial</b> has registered an electricity consumption beyond %limit_up watts, at <b>%event_time</b>.
    <p>Best Regards,</p>
    <p>mySmartGrid System</p>";

  _notification_send_emails($message, $sql);
}

function notification_mail($key, &$message, $params) {

  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}
