<?php
// $Id$

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function device_checkup_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#device_checkup":
      $output = '<p>'.t("Checks the device status up, by looking it up in a database and showing it to the user").'</p>';
      break;
  }
  return $output;
}

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the onthisdate module
 */
function device_checkup_perm() {
  return array('Device Check Up');
}

function device_checkup_menu() {
  $items = array();
  $items['devicecheckup'] = array(
    'title' => 'Device Check Up',
    'page callback' => 'device_checkup_print',
    'access arguments' => array('device_checkup'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function device_checkup_print() {
  $output .= drupal_get_form('device_checkup_print_form');
  return $output;
}

function device_checkup_print_form() {
  $form['serial'] = array(
    '#type' => 'textfield',
    '#title' => t("Serial"),
    '#size' => 32,
    '#maxlength' => 40,
    '#required' => 1,
    '#description' => t('Enter the device serial number you want to check up')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t("Check Up")
  );
  return $form;
}

function device_checkup_print_form_submit($form, &$form_state) {

  $serial = $form_state['values']['serial'];

  $sql = "SELECT
             d.access AS latest_heartbeat,
             m.access AS integrity
           FROM
             {logger_devices} d,
             {logger_meters} m
           WHERE
             m.device = d.device AND
             m.type = 'electricity' AND
             d.serial = %d";

  $result = db_query($sql, $serial);
  $device = db_fetch_object($result);

  if($device) {

    if ($device->latest_heartbeat > 0) {

      drupal_set_message(t('Latest heartbeat received at: ') . date('D, d M Y H:i:s', $device->latest_heartbeat));
 
      if ($device->integrity == 0) {
	      drupal_set_message(t('It contains an invalid measurement. The device can be either malfunctioning or misconfigured.'));
      }

    } else {
      drupal_set_message(t('No heartbeat has yet been received from this device.'));
    }

  } else {
    drupal_set_message(t('No device was found with such serial number.'));
  }
}

function device_checkup_settings() {
  $output .= drupal_get_form('device_checkup_form');
  return $output;
}

/**
* Display form to submit key
* @return content to display
*/
function device_checkup_form() {

  $form['device_checkup'] = array(
    '#type' => 'textfield',
    '#title' => t('Device Check Up'),
    '#size' => 30,
    '#maxlength' => 32,
    '#description' => t('Enter the device serial number'),
    '#default_value' => ''
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Check Up')
  );
  return $form;
}

function device_checkup_settings_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}
