/** License: https://www.mysmartgrid.de/sites/all/modules/logger/js/dygraph/dygraph.js */
Dygraph=function(a,b,c){0<arguments.length&&(4==arguments.length?(this.warn("Using deprecated four-argument dygraph constructor"),this.__old_init__(a,b,arguments[2],arguments[3])):this.__init__(a,b,c))};Dygraph.NAME="Dygraph";Dygraph.VERSION="1.2";Dygraph.__repr__=function(){return"["+this.NAME+" "+this.VERSION+"]"};Dygraph.toString=function(){return this.__repr__()};Dygraph.DEFAULT_ROLL_PERIOD=1;Dygraph.DEFAULT_WIDTH=480;Dygraph.DEFAULT_HEIGHT=320;Dygraph.AXIS_LINE_WIDTH=0.3;
Dygraph.DEFAULT_ATTRS={highlightCircleSize:3,pixelsPerXLabel:60,pixelsPerYLabel:30,labelsDivWidth:250,labelsDivStyles:{},labelsSeparateLines:!1,labelsShowZeroValues:!0,labelsKMB:!1,labelsKMG2:!1,showLabelsOnHighlight:!0,yValueFormatter:function(a){return Dygraph.round_(a,2)},strokeWidth:1,axisTickSize:3,axisLabelFontSize:14,xAxisLabelWidth:50,yAxisLabelWidth:50,xAxisLabelFormatter:Dygraph.dateAxisFormatter,rightGap:5,showRoller:!1,xValueFormatter:Dygraph.dateString_,xValueParser:Dygraph.dateParser,
xTicker:Dygraph.dateTicker,delimiter:",",logScale:!1,sigma:2,errorBars:!1,fractions:!1,wilsonInterval:!0,customBars:!1,fillGraph:!1,fillAlpha:0.15,connectSeparatedPoints:!1,stackedGraph:!1,hideOverlayOnMouseOut:!0,stepPlot:!1,avoidMinZero:!1};Dygraph.DEBUG=1;Dygraph.INFO=2;Dygraph.WARNING=3;Dygraph.ERROR=3;Dygraph.HORIZONTAL=1;Dygraph.VERTICAL=2;Dygraph.addedAnnotationCSS=!1;
Dygraph.prototype.__old_init__=function(a,b,c,e){if(null!=c){for(var d=["Date"],g=0;g<c.length;g++)d.push(c[g]);Dygraph.update(e,{labels:d})}this.__init__(a,b,e)};
Dygraph.prototype.__init__=function(a,b,c){if(/MSIE/.test(navigator.userAgent)&&!window.opera&&"undefined"!=typeof G_vmlCanvasManager&&"complete"!=document.readyState){var e=this;setTimeout(function(){e.__init__(a,b,c)},100)}null==c&&(c={});this.maindiv_=a;this.file_=b;this.rollPeriod_=c.rollPeriod||Dygraph.DEFAULT_ROLL_PERIOD;this.previousVerticalX_=-1;this.fractions_=c.fractions||!1;this.dateWindow_=c.dateWindow||null;this.wilsonInterval_=c.wilsonInterval||!0;this.is_initial_draw_=!0;this.annotations_=
[];a.innerHTML="";""==a.style.width&&(a.style.width=(c.width||Dygraph.DEFAULT_WIDTH)+"px");""==a.style.height&&(a.style.height=(c.height||Dygraph.DEFAULT_HEIGHT)+"px");this.width_=parseInt(a.style.width,10);this.height_=parseInt(a.style.height,10);a.style.width.indexOf("%")==a.style.width.length-1&&(this.width_=a.offsetWidth);a.style.height.indexOf("%")==a.style.height.length-1&&(this.height_=a.offsetHeight);0==this.width_&&this.error("dygraph has zero width. Please specify a width in pixels.");0==
this.height_&&this.error("dygraph has zero height. Please specify a height in pixels.");c.stackedGraph&&(c.fillGraph=!0);this.user_attrs_={};Dygraph.update(this.user_attrs_,c);this.attrs_={};Dygraph.update(this.attrs_,Dygraph.DEFAULT_ATTRS);this.boundaryIds_=[];this.labelsFromCSV_=null==this.attr_("labels");this.createInterface_();this.start_()};
Dygraph.prototype.attr_=function(a,b){return b&&"undefined"!=typeof this.user_attrs_[b]&&null!=this.user_attrs_[b]&&"undefined"!=typeof this.user_attrs_[b][a]?this.user_attrs_[b][a]:"undefined"!=typeof this.user_attrs_[a]?this.user_attrs_[a]:"undefined"!=typeof this.attrs_[a]?this.attrs_[a]:null};
Dygraph.prototype.log=function(a,b){if("undefined"!=typeof console)switch(a){case Dygraph.DEBUG:console.debug("dygraphs: "+b);break;case Dygraph.INFO:console.info("dygraphs: "+b);break;case Dygraph.WARNING:console.warn("dygraphs: "+b);break;case Dygraph.ERROR:console.error("dygraphs: "+b)}};Dygraph.prototype.info=function(a){this.log(Dygraph.INFO,a)};Dygraph.prototype.warn=function(a){this.log(Dygraph.WARNING,a)};Dygraph.prototype.error=function(a){this.log(Dygraph.ERROR,a)};
Dygraph.prototype.rollPeriod=function(){return this.rollPeriod_};Dygraph.prototype.xAxisRange=function(){return this.dateWindow_?this.dateWindow_:[this.rawData_[0][0],this.rawData_[this.rawData_.length-1][0]]};Dygraph.prototype.yAxisRange=function(a){"undefined"==typeof a&&(a=0);return 0>a||a>=this.axes_.length?null:[this.axes_[a].computedValueRange[0],this.axes_[a].computedValueRange[1]]};
Dygraph.prototype.yAxisRanges=function(){for(var a=[],b=0;b<this.axes_.length;b++)a.push(this.yAxisRange(b));return a};Dygraph.prototype.toDomCoords=function(a,b,c){var e=[null,null],d=this.plotter_.area;if(null!==a){var g=this.xAxisRange();e[0]=d.x+(a-g[0])/(g[1]-g[0])*d.w}null!==b&&(a=this.yAxisRange(c),e[1]=d.y+(a[1]-b)/(a[1]-a[0])*d.h);return e};
Dygraph.prototype.toDataCoords=function(a,b,c){var e=[null,null],d=this.plotter_.area;if(null!==a){var g=this.xAxisRange();e[0]=g[0]+(a-d.x)/d.w*(g[1]-g[0])}null!==b&&(a=this.yAxisRange(c),e[1]=a[0]+(d.h-b)/d.h*(a[1]-a[0]));return e};Dygraph.prototype.numColumns=function(){return this.rawData_[0].length};Dygraph.prototype.numRows=function(){return this.rawData_.length};Dygraph.prototype.getValue=function(a,b){return 0>a||a>this.rawData_.length||0>b||b>this.rawData_[a].length?null:this.rawData_[a][b]};
Dygraph.addEvent=function(a,b,c){var e=function(a){a||(a=window.event);c(a)};window.addEventListener?a.addEventListener(b,e,!1):a.attachEvent("on"+b,e)};
Dygraph.prototype.createInterface_=function(){var a=this.maindiv_;this.graphDiv=document.createElement("div");this.graphDiv.style.width=this.width_+"px";this.graphDiv.style.height=this.height_+"px";a.appendChild(this.graphDiv);this.canvas_=Dygraph.createCanvas();this.canvas_.style.position="absolute";this.canvas_.width=this.width_;this.canvas_.height=this.height_;this.canvas_.style.width=this.width_+"px";this.canvas_.style.height=this.height_+"px";this.hidden_=this.createPlotKitCanvas_(this.canvas_);
this.graphDiv.appendChild(this.hidden_);this.graphDiv.appendChild(this.canvas_);this.mouseEventElement_=this.canvas_;var b=this;Dygraph.addEvent(this.mouseEventElement_,"mousemove",function(a){b.mouseMove_(a)});Dygraph.addEvent(this.mouseEventElement_,"mouseout",function(a){b.mouseOut_(a)});this.layoutOptions_={xOriginIsZero:!1};Dygraph.update(this.layoutOptions_,this.attrs_);Dygraph.update(this.layoutOptions_,this.user_attrs_);Dygraph.update(this.layoutOptions_,{errorBars:this.attr_("errorBars")||
this.attr_("customBars")});this.layout_=new DygraphLayout(this,this.layoutOptions_);this.renderOptions_={colorScheme:this.colors_,strokeColor:null,axisLineWidth:Dygraph.AXIS_LINE_WIDTH};Dygraph.update(this.renderOptions_,this.attrs_);Dygraph.update(this.renderOptions_,this.user_attrs_);this.createStatusMessage_();this.createDragInterface_()};
Dygraph.prototype.destroy=function(){var a=function(b){for(;b.hasChildNodes();)a(b.firstChild),b.removeChild(b.firstChild)};a(this.maindiv_);var b=function(a){for(var b in a)"object"===typeof a[b]&&(a[b]=null)};b(this.layout_);b(this.plotter_);b(this)};
Dygraph.prototype.createPlotKitCanvas_=function(a){var b=Dygraph.createCanvas();b.style.position="absolute";b.style.top=a.style.top;b.style.left=a.style.left;b.width=this.width_;b.height=this.height_;b.style.width=this.width_+"px";b.style.height=this.height_+"px";return b};
Dygraph.hsvToRGB=function(a,b,c){var e,d,g;if(0===b)g=d=e=c;else{var f=Math.floor(6*a),h=6*a-f;a=c*(1-b);var j=c*(1-b*h);b=c*(1-b*(1-h));switch(f){case 1:e=j;d=c;g=a;break;case 2:e=a;d=c;g=b;break;case 3:e=a;d=j;g=c;break;case 4:e=b;d=a;g=c;break;case 5:e=c;d=a;g=j;break;case 6:case 0:e=c,d=b,g=a}}e=Math.floor(255*e+0.5);d=Math.floor(255*d+0.5);g=Math.floor(255*g+0.5);return"rgb("+e+","+d+","+g+")"};
Dygraph.prototype.setColors_=function(){var a=this.attr_("labels").length-1;this.colors_=[];var b=this.attr_("colors");if(b)for(d=0;d<a;d++)this.visibility()[d]&&this.colors_.push(b[d%b.length]);else for(var b=this.attr_("colorSaturation")||1,c=this.attr_("colorValue")||0.5,e=Math.ceil(a/2),d=1;d<=a;d++)if(this.visibility()[d-1]){var g=1*(d%2?Math.ceil(d/2):e+d/2)/(1+a);this.colors_.push(Dygraph.hsvToRGB(g,b,c))}this.renderOptions_.colorScheme=this.colors_;Dygraph.update(this.plotter_.options,this.renderOptions_);
Dygraph.update(this.layoutOptions_,this.user_attrs_);Dygraph.update(this.layoutOptions_,this.attrs_)};Dygraph.prototype.getColors=function(){return this.colors_};Dygraph.findPosX=function(a){var b=0;if(a.offsetParent)for(;;){b+=a.offsetLeft;if(!a.offsetParent)break;a=a.offsetParent}else a.x&&(b+=a.x);return b};Dygraph.findPosY=function(a){var b=0;if(a.offsetParent)for(;;){b+=a.offsetTop;if(!a.offsetParent)break;a=a.offsetParent}else a.y&&(b+=a.y);return b};
Dygraph.prototype.createStatusMessage_=function(){var a=this.user_attrs_.labelsDiv;if(a&&null!=a&&("string"==typeof a||a instanceof String))this.user_attrs_.labelsDiv=document.getElementById(a);if(!this.attr_("labelsDiv")){a=this.attr_("labelsDivWidth");a={position:"absolute",fontSize:"14px",zIndex:10,width:a+"px",top:"0px",left:this.width_-a-2+"px",background:"white",textAlign:"left",overflow:"hidden"};Dygraph.update(a,this.attr_("labelsDivStyles"));var b=document.createElement("div"),c;for(c in a)a.hasOwnProperty(c)&&
(b.style[c]=a[c]);this.graphDiv.appendChild(b);this.attrs_.labelsDiv=b}};Dygraph.prototype.positionLabelsDiv_=function(){if(!this.user_attrs_.hasOwnProperty("labelsDiv")){var a=this.plotter_.area;this.attr_("labelsDiv").style.left=a.x+a.w-this.attr_("labelsDivWidth")-1+"px"}};
Dygraph.prototype.createRollInterface_=function(){this.roller_||(this.roller_=document.createElement("input"),this.roller_.type="text",this.roller_.style.display="none",this.graphDiv.appendChild(this.roller_));var a=this.attr_("showRoller")?"block":"none",a={position:"absolute",zIndex:10,top:this.plotter_.area.h-25+"px",left:this.plotter_.area.x+1+"px",display:a};this.roller_.size="2";this.roller_.value=this.rollPeriod_;for(var b in a)a.hasOwnProperty(b)&&(this.roller_.style[b]=a[b]);var c=this;this.roller_.onchange=
function(){c.adjustRoll(c.roller_.value)}};Dygraph.pageX=function(a){if(a.pageX)return!a.pageX||0>a.pageX?0:a.pageX;var b=document,c=document.body;return a.clientX+(b.scrollLeft||c.scrollLeft)-(b.clientLeft||0)};Dygraph.pageY=function(a){if(a.pageY)return!a.pageY||0>a.pageY?0:a.pageY;var b=document,c=document.body;return a.clientY+(b.scrollTop||c.scrollTop)-(b.clientTop||0)};
Dygraph.prototype.createDragInterface_=function(){var a=this,b=!1,c=!1,e=!1,d=null,g=null,f=null,h=null,j=null,m=null,k=null,n=null,l=null,p=null,q=0,s=0;Dygraph.addEvent(this.mouseEventElement_,"mousemove",function(r){if(b){f=Dygraph.pageX(r)-q;h=Dygraph.pageY(r)-s;r=Math.abs(d-f);var v=Math.abs(g-h);j=r<v/2?Dygraph.VERTICAL:Dygraph.HORIZONTAL;a.drawZoomRect_(j,d,f,g,h,n,m,k);m=f;k=h;n=j}else if(c){f=Dygraph.pageX(r)-q;h=Dygraph.pageY(r)-s;r=l-f/a.width_*p;a.dateWindow_=[r,r+p];if(e){r=h/a.height_;
for(v=0;v<a.axes_.length;v++){var w=a.axes_[v],t=w.draggingValue+r*w.dragValueRange;w.valueWindow=[t-w.dragValueRange,t]}}a.drawGraph_()}});Dygraph.addEvent(this.mouseEventElement_,"mousedown",function(f){f.preventDefault?f.preventDefault():(f.returnValue=!1,f.cancelBubble=!0);q=Dygraph.findPosX(a.canvas_);s=Dygraph.findPosY(a.canvas_);d=Dygraph.pageX(f)-q;g=Dygraph.pageY(f)-s;if(f.altKey||f.shiftKey){var h=!1;for(f=0;f<a.axes_.length;f++)if(a.axes_[f].valueWindow||a.axes_[f].valueRange){h=!0;break}if(a.dateWindow_||
h){c=!0;h=a.xAxisRange();p=h[1]-h[0];e=!1;for(f=0;f<a.axes_.length;f++){var j=a.axes_[f],k=a.yAxisRange(f);j.dragValueRange=k[1]-k[0];k=a.toDataCoords(null,g,f);j.draggingValue=k[1];if(j.valueWindow||j.valueRange)e=!0}l=d/a.width_*p+h[0]}}else b=!0});Dygraph.addEvent(document,"mouseup",function(){if(b||c)b=!1,g=d=null;if(c){c=!1;p=l=null;for(var e=0;e<a.axes_.length;e++)delete a.axes_[e].draggingValue,delete a.axes_[e].dragValueRange}});Dygraph.addEvent(this.mouseEventElement_,"mouseout",function(){b&&
(h=f=null)});Dygraph.addEvent(this.mouseEventElement_,"mouseup",function(k){if(b){b=!1;f=Dygraph.pageX(k)-q;h=Dygraph.pageY(k)-s;var m=Math.abs(f-d),n=Math.abs(h-g);if(2>m&&(2>n&&void 0!=a.lastx_&&-1!=a.lastx_)&&(null!=a.attr_("clickCallback")&&a.attr_("clickCallback")(k,a.lastx_,a.selPoints_),a.attr_("pointClickCallback"))){for(var t=-1,y=0,x=0;x<a.selPoints_.length;x++){var u=a.selPoints_[x],u=Math.pow(u.canvasx-f,2)+Math.pow(u.canvasy-h,2);if(-1==t&&0<u||u<y)y=u,t=x}a.attr_("highlightCircleSize");
25>=y&&a.attr_("pointClickCallback")(k,a.selPoints_[t])}10<=m&&j==Dygraph.HORIZONTAL?a.doZoomX_(Math.min(d,f),Math.max(d,f)):10<=n&&j==Dygraph.VERTICAL?a.doZoomY_(Math.min(g,h),Math.max(g,h)):a.canvas_.getContext("2d").clearRect(0,0,a.canvas_.width,a.canvas_.height);g=d=null}c&&(e=c=!1,valueRange=p=l=null)});Dygraph.addEvent(this.mouseEventElement_,"dblclick",function(b){!b.altKey&&!b.shiftKey&&a.doUnzoom_()})};
Dygraph.prototype.drawZoomRect_=function(a,b,c,e,d,g,f,h){var j=this.canvas_.getContext("2d");g==Dygraph.HORIZONTAL?j.clearRect(Math.min(b,f),0,Math.abs(b-f),this.height_):g==Dygraph.VERTICAL&&j.clearRect(0,Math.min(e,h),this.width_,Math.abs(e-h));a==Dygraph.HORIZONTAL&&(c&&b)&&(j.fillStyle="rgba(128,128,128,0.33)",j.fillRect(Math.min(b,c),0,Math.abs(c-b),this.height_));a==Dygraph.VERTICAL&&(d&&e)&&(j.fillStyle="rgba(128,128,128,0.33)",j.fillRect(0,Math.min(e,d),this.width_,Math.abs(d-e)))};
Dygraph.prototype.doZoomX_=function(a,b){var c=this.toDataCoords(a,null),e=c[0],c=this.toDataCoords(b,null);this.doZoomXDates_(e,c[0])};Dygraph.prototype.doZoomXDates_=function(a,b){this.dateWindow_=[a,b];this.drawGraph_();if(this.attr_("zoomCallback")){var c=this.yAxisRange();this.attr_("zoomCallback")(a,b,c[0],c[1])}};
Dygraph.prototype.doZoomY_=function(a,b){for(var c=[],e=0;e<this.axes_.length;e++){var d=this.toDataCoords(null,a,e),g=this.toDataCoords(null,b,e);this.axes_[e].valueWindow=[g[1],d[1]];c.push([g[1],d[1]])}this.drawGraph_();this.attr_("zoomCallback")&&(c=this.xAxisRange(),this.attr_("zoomCallback")(c[0],c[1],this.yAxisRanges()))};
Dygraph.prototype.doUnzoom_=function(){var a=!1;null!=this.dateWindow_&&(a=!0,this.dateWindow_=null);for(var b=0;b<this.axes_.length;b++)null!=this.axes_[b].valueWindow&&(a=!0,delete this.axes_[b].valueWindow);a&&(this.drawGraph_(),this.attr_("zoomCallback")&&(a=this.rawData_[0][0],b=this.rawData_[this.rawData_.length-1][0],this.attr_("zoomCallback")(a,b,this.yAxisRanges())))};
Dygraph.prototype.mouseMove_=function(a){for(var b=Dygraph.pageX(a)-Dygraph.findPosX(this.mouseEventElement_),c=this.layout_.points,e=-1,d=1E100,g=-1,f=0;f<c.length;f++)if(null!=c[f]){var h=Math.abs(c[f].canvasx-b);h>d||(d=h,g=f)}0<=g&&(e=c[g].xval);f=c[c.length-1];null!=f&&b>f.canvasx&&(e=c[c.length-1].xval);this.selPoints_=[];d=c.length;if(this.attr_("stackedGraph")){b=0;for(f=d-1;0<=f;f--)if(c[f].xval==e){var d={},j;for(j in c[f])d[j]=c[f][j];d.yval-=b;b+=d.yval;this.selPoints_.push(d)}this.selPoints_.reverse()}else for(f=
0;f<d;f++)c[f].xval==e&&this.selPoints_.push(c[f]);this.attr_("highlightCallback")&&(c=this.lastx_,null!==c&&e!=c&&this.attr_("highlightCallback")(a,e,this.selPoints_,this.idxToRow_(g)));this.lastx_=e;this.updateSelection_()};Dygraph.prototype.idxToRow_=function(a){if(0>a)return-1;for(var b in this.layout_.datasets){if(a<this.layout_.datasets[b].length)return this.boundaryIds_[0][0]+a;a-=this.layout_.datasets[b].length}return-1};
Dygraph.prototype.updateSelection_=function(){var a=this.canvas_.getContext("2d");if(0<=this.previousVerticalX_){for(var b=0,c=this.attr_("labels"),e=1;e<c.length;e++){var d=this.attr_("highlightCircleSize",c[e]);d>b&&(b=d)}a.clearRect(this.previousVerticalX_-b-1,0,2*b+2,this.height_)}if(0<this.selPoints_.length){b=this.selPoints_[0].canvasx;c=this.attr_("xValueFormatter")(this.lastx_,this)+":";d=this.attr_("yValueFormatter");if(this.attr_("showLabelsOnHighlight")){for(e=0;e<this.selPoints_.length;e++)if((this.attr_("labelsShowZeroValues")||
0!=this.selPoints_[e].yval)&&this.selPoints_[e].canvasy&&!isNaN(this.selPoints_[e].canvasy)){this.attr_("labelsSeparateLines")&&(c+="<br/>");var g=this.selPoints_[e],f=new RGBColor(this.plotter_.colors[g.name]),h=d(g.yval),c=c+(" <b><font color='"+f.toHex()+"'>"+g.name+"</font></b>:"+h)}this.attr_("labelsDiv").innerHTML=c}a.save();for(e=0;e<this.selPoints_.length;e++)this.selPoints_[e].canvasy&&!isNaN(this.selPoints_[e].canvasy)&&(c=this.attr_("highlightCircleSize",this.selPoints_[e].name),a.beginPath(),
a.fillStyle=this.plotter_.colors[this.selPoints_[e].name],a.arc(b,this.selPoints_[e].canvasy,c,0,2*Math.PI,!1),a.fill());a.restore();this.previousVerticalX_=b}};
Dygraph.prototype.setSelection=function(a){this.selPoints_=[];var b=0;!1!==a&&(a-=this.boundaryIds_[0][0]);if(!1!==a&&0<=a)for(var c in this.layout_.datasets){if(a<this.layout_.datasets[c].length){var e=this.layout_.points[b+a];this.attr_("stackedGraph")&&(e=this.layout_.unstackPointAtIndex(b+a));this.selPoints_.push(e)}b+=this.layout_.datasets[c].length}this.selPoints_.length?(this.lastx_=this.selPoints_[0].xval,this.updateSelection_()):(this.lastx_=-1,this.clearSelection())};
Dygraph.prototype.mouseOut_=function(a){this.attr_("unhighlightCallback")&&this.attr_("unhighlightCallback")(a);this.attr_("hideOverlayOnMouseOut")&&this.clearSelection()};Dygraph.prototype.clearSelection=function(){this.canvas_.getContext("2d").clearRect(0,0,this.width_,this.height_);this.attr_("labelsDiv").innerHTML="";this.selPoints_=[];this.lastx_=-1};
Dygraph.prototype.getSelection=function(){if(!this.selPoints_||1>this.selPoints_.length)return-1;for(var a=0;a<this.layout_.points.length;a++)if(this.layout_.points[a].x==this.selPoints_[0].x)return a+this.boundaryIds_[0][0];return-1};Dygraph.zeropad=function(a){return 10>a?"0"+a:""+a};Dygraph.hmsString_=function(a){var b=Dygraph.zeropad;a=new Date(a);return a.getSeconds()?b(a.getHours())+":"+b(a.getMinutes())+":"+b(a.getSeconds()):b(a.getHours())+":"+b(a.getMinutes())};
Dygraph.dateAxisFormatter=function(a,b){return b>=Dygraph.MONTHLY?a.strftime("%b %y"):0==3600*a.getHours()+60*a.getMinutes()+a.getSeconds()+a.getMilliseconds()||b>=Dygraph.DAILY?(new Date(a.getTime()+36E5)).strftime("%d%b"):Dygraph.hmsString_(a.getTime())};Dygraph.dateString_=function(a){var b=Dygraph.zeropad,c=new Date(a),e=""+c.getFullYear(),d=b(c.getMonth()+1),b=b(c.getDate()),g="";3600*c.getHours()+60*c.getMinutes()+c.getSeconds()&&(g=" "+Dygraph.hmsString_(a));return e+"/"+d+"/"+b+g};
Dygraph.round_=function(a,b){var c=Math.pow(10,b);return Math.round(a*c)/c};Dygraph.prototype.loadedEvent_=function(a){this.rawData_=this.parseCSV_(a);this.predraw_()};Dygraph.prototype.months="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");Dygraph.prototype.quarters=["Jan","Apr","Jul","Oct"];
Dygraph.prototype.addXTicks_=function(){var a,b;this.dateWindow_?(a=this.dateWindow_[0],b=this.dateWindow_[1]):(a=this.rawData_[0][0],b=this.rawData_[this.rawData_.length-1][0]);a=this.attr_("xTicker")(a,b,this);this.layout_.updateOptions({xTicks:a})};Dygraph.SECONDLY=0;Dygraph.TWO_SECONDLY=1;Dygraph.FIVE_SECONDLY=2;Dygraph.TEN_SECONDLY=3;Dygraph.THIRTY_SECONDLY=4;Dygraph.MINUTELY=5;Dygraph.TWO_MINUTELY=6;Dygraph.FIVE_MINUTELY=7;Dygraph.TEN_MINUTELY=8;Dygraph.THIRTY_MINUTELY=9;Dygraph.HOURLY=10;
Dygraph.TWO_HOURLY=11;Dygraph.SIX_HOURLY=12;Dygraph.DAILY=13;Dygraph.WEEKLY=14;Dygraph.MONTHLY=15;Dygraph.QUARTERLY=16;Dygraph.BIANNUAL=17;Dygraph.ANNUAL=18;Dygraph.DECADAL=19;Dygraph.NUM_GRANULARITIES=20;Dygraph.SHORT_SPACINGS=[];Dygraph.SHORT_SPACINGS[Dygraph.SECONDLY]=1E3;Dygraph.SHORT_SPACINGS[Dygraph.TWO_SECONDLY]=2E3;Dygraph.SHORT_SPACINGS[Dygraph.FIVE_SECONDLY]=5E3;Dygraph.SHORT_SPACINGS[Dygraph.TEN_SECONDLY]=1E4;Dygraph.SHORT_SPACINGS[Dygraph.THIRTY_SECONDLY]=3E4;
Dygraph.SHORT_SPACINGS[Dygraph.MINUTELY]=6E4;Dygraph.SHORT_SPACINGS[Dygraph.TWO_MINUTELY]=12E4;Dygraph.SHORT_SPACINGS[Dygraph.FIVE_MINUTELY]=3E5;Dygraph.SHORT_SPACINGS[Dygraph.TEN_MINUTELY]=6E5;Dygraph.SHORT_SPACINGS[Dygraph.THIRTY_MINUTELY]=18E5;Dygraph.SHORT_SPACINGS[Dygraph.HOURLY]=36E5;Dygraph.SHORT_SPACINGS[Dygraph.TWO_HOURLY]=72E5;Dygraph.SHORT_SPACINGS[Dygraph.SIX_HOURLY]=216E5;Dygraph.SHORT_SPACINGS[Dygraph.DAILY]=864E5;Dygraph.SHORT_SPACINGS[Dygraph.WEEKLY]=6048E5;
Dygraph.prototype.NumXTicks=function(a,b,c){if(c<Dygraph.MONTHLY)return Math.floor(0.5+1*(b-a)/Dygraph.SHORT_SPACINGS[c]);var e=1,d=12;c==Dygraph.QUARTERLY&&(d=3);c==Dygraph.BIANNUAL&&(d=2);c==Dygraph.ANNUAL&&(d=1);c==Dygraph.DECADAL&&(d=1,e=10);return Math.floor(0.5+1*(1*(b-a)/31557807360)*d/e)};
Dygraph.prototype.GetXAxis=function(a,b,c){var e=this.attr_("xAxisLabelFormatter"),d=[];if(c<Dygraph.MONTHLY){var g=Dygraph.SHORT_SPACINGS[c],f=g/1E3;a=new Date(a);if(60>=f){var h=a.getSeconds();a.setSeconds(h-h%f)}else a.setSeconds(0),f/=60,60>=f?(h=a.getMinutes(),a.setMinutes(h-h%f)):(a.setMinutes(0),f/=60,24>=f?(h=a.getHours(),a.setHours(h-h%f)):(a.setHours(0),7==f/24&&a.setDate(a.getDate()-a.getDay())));for(var j=a=a.getTime();j<=b;j+=g)d.push({v:j,label:e(new Date(j),c)})}else{f=1;c==Dygraph.MONTHLY?
g=[0,1,2,3,4,5,6,7,8,9,10,11,12]:c==Dygraph.QUARTERLY?g=[0,3,6,9]:c==Dygraph.BIANNUAL?g=[0,6]:c==Dygraph.ANNUAL?g=[0]:c==Dygraph.DECADAL&&(g=[0],f=10);for(var j=(new Date(a)).getFullYear(),h=(new Date(b)).getFullYear(),m=Dygraph.zeropad,k=j;k<=h;k++)if(0==k%f)for(var n=0;n<g.length;n++)j=k+"/"+m(1+g[n])+"/01",j=Date.parse(j),j<a||j>b||d.push({v:j,label:e(new Date(j),c)})}return d};
Dygraph.dateTicker=function(a,b,c){for(var e=-1,d=0;d<Dygraph.NUM_GRANULARITIES;d++){var g=c.NumXTicks(a,b,d);if(c.width_/g>=c.attr_("pixelsPerXLabel")){e=d;break}}if(0<=e)return c.GetXAxis(a,b,e)};
Dygraph.numericTicks=function(a,b,c,e,d){var g=function(a){return e&&e.hasOwnProperty(a)?e[a]:c.attr_(a)},f=[];if(d)for(var h=0;h<d.length;h++)f.push({v:d[h]});else{for(var j=g("labelsKMG2")?[1,2,4,8]:[1,2,5],m,k,n,l,p=g("pixelsPerYLabel"),h=-10;50>h;h++){var q=g("labelsKMG2")?Math.pow(16,h):Math.pow(10,h);for(d=0;d<j.length;d++){m=q*j[d];k=Math.floor(a/m)*m;n=Math.ceil(b/m)*m;l=Math.abs(n-k)/m;var s=c.height_/l;if(s>p)break}if(s>p)break}k>n&&(m*=-1);for(h=0;h<l;h++)a=k+h*m,f.push({v:a})}var r;m=
[];g("labelsKMB")&&(r=1E3,m=["K","M","B","T"]);g("labelsKMG2")&&(r&&c.warn("Setting both labelsKMB and labelsKMG2. Pick one!"),r=1024,m=["k","M","G","T"]);g=g("yAxisLabelFormatter")?g("yAxisLabelFormatter"):g("yValueFormatter");for(h=0;h<f.length;h++){a=f[h].v;k=Math.abs(a);l=void 0!=g?g(a):Dygraph.round_(a,2);if(m.length){b=r*r*r*r;for(d=3;0<=d;d--,b/=r)if(k>=b){l=Dygraph.round_(a/b,1)+m[d];break}}f[h].label=l}return f};
Dygraph.prototype.extremeValues_=function(a){var b=null,c=null;if(this.attr_("errorBars")||this.attr_("customBars"))for(var e=0;e<a.length;e++){var d=a[e][1][0];if(d){var g=d-a[e][1][1],f=d+a[e][1][2];g>d&&(g=d);f<d&&(f=d);if(null==c||f>c)c=f;if(null==b||g<b)b=g}}else for(e=0;e<a.length;e++)if(d=a[e][1],!(null===d||isNaN(d))){if(null==c||d>c)c=d;if(null==b||d<b)b=d}return[b,c]};
Dygraph.prototype.predraw_=function(){this.computeYAxes_();this.plotter_&&this.plotter_.clear();this.plotter_=new DygraphCanvasRenderer(this,this.hidden_,this.layout_,this.renderOptions_);this.createRollInterface_();this.positionLabelsDiv_();this.drawGraph_()};
Dygraph.prototype.drawGraph_=function(){var a=this.rawData_,b=this.is_initial_draw_;this.is_initial_draw_=!1;this.layout_.removeAllDatasets();this.setColors_();this.attrs_.pointSize=0.5*this.attr_("highlightCircleSize");for(var c=[],e=[],d={},g=a[0].length-1;1<=g;g--)if(this.visibility()[g-1]){for(var f=this.attr_("labels")[g],h=this.attr_("connectSeparatedPoints",g),j=[],m=0;m<a.length;m++)(null!=a[m][g]||!h)&&j.push([a[m][0],a[m][g]]);j=this.rollingAverage(j,this.rollPeriod_);m=this.attr_("errorBars")||
this.attr_("customBars");if(this.dateWindow_){for(var h=this.dateWindow_[0],k=this.dateWindow_[1],n=[],l=null,p=null,q=0;q<j.length;q++)j[q][0]>=h&&null===l&&(l=q),j[q][0]<=k&&(p=q);null===l&&(l=0);0<l&&l--;null===p&&(p=j.length-1);p<j.length-1&&p++;this.boundaryIds_[g-1]=[l,p];for(q=l;q<=p;q++)n.push(j[q]);j=n}else this.boundaryIds_[g-1]=[0,j.length-1];h=this.extremeValues_(j);if(m)for(m=0;m<j.length;m++)val=[j[m][0],j[m][1][0],j[m][1][1],j[m][1][2]],j[m]=val;else if(this.attr_("stackedGraph")){k=
j.length;for(m=0;m<k;m++)l=j[m][0],void 0===c[l]&&(c[l]=0),n=j[m][1],c[l]+=n,j[m]=[l,c[l]],c[l]>h[1]&&(h[1]=c[l]),c[l]<h[0]&&(h[0]=c[l])}d[f]=h;e[g]=j}for(g=1;g<e.length;g++)this.visibility()[g-1]&&this.layout_.addDataset(this.attr_("labels")[g],e[g]);a=this.computeYAxisRanges_(d);this.layout_.updateOptions({yAxes:a[0],seriesToAxisMap:a[1]});this.addXTicks_();this.layout_.updateOptions({dateWindow:this.dateWindow_});this.layout_.evaluateWithError();this.plotter_.clear();this.plotter_.render();this.canvas_.getContext("2d").clearRect(0,
0,this.canvas_.width,this.canvas_.height);null!==this.attr_("drawCallback")&&this.attr_("drawCallback")(this,b)};
Dygraph.prototype.computeYAxes_=function(){this.axes_=[{}];this.seriesToAxisMap_={};for(var a=this.attr_("labels"),b={},c=1;c<a.length;c++)b[a[c]]=c-1;for(var e="includeZero valueRange labelsKMB labelsKMG2 pixelsPerYLabel yAxisLabelWidth axisLabelFontSize axisTickSize".split(" "),c=0;c<e.length;c++){var d=e[c],g=this.attr_(d);g&&(this.axes_[0][d]=g)}for(var f in b)b.hasOwnProperty(f)&&(c=this.attr_("axis",f),null==c?this.seriesToAxisMap_[f]=0:"object"==typeof c&&(e={},Dygraph.update(e,this.axes_[0]),
Dygraph.update(e,{valueRange:null}),Dygraph.update(e,c),this.axes_.push(e),this.seriesToAxisMap_[f]=this.axes_.length-1));for(f in b)if(b.hasOwnProperty(f)&&(c=this.attr_("axis",f),"string"==typeof c)){if(!this.seriesToAxisMap_.hasOwnProperty(c))return this.error("Series "+f+" wants to share a y-axis with series "+c+", which does not define its own axis."),null;this.seriesToAxisMap_[f]=this.seriesToAxisMap_[c]}b={};f=this.visibility();for(c=1;c<a.length;c++)e=a[c],f[c-1]&&(b[e]=this.seriesToAxisMap_[e]);
this.seriesToAxisMap_=b};Dygraph.prototype.numAxes=function(){var a=0,b;for(b in this.seriesToAxisMap_)if(this.seriesToAxisMap_.hasOwnProperty(b)){var c=this.seriesToAxisMap_[b];c>a&&(a=c)}return 1+a};
Dygraph.prototype.computeYAxisRanges_=function(a){var b=[],c;for(c in this.seriesToAxisMap_)if(this.seriesToAxisMap_.hasOwnProperty(c)){for(var e=this.seriesToAxisMap_[c];b.length<=e;)b.push([]);b[e].push(c)}for(e=0;e<this.axes_.length;e++){var d=this.axes_[e];if(d.valueWindow)d.computedValueRange=[d.valueWindow[0],d.valueWindow[1]];else if(d.valueRange)d.computedValueRange=[d.valueRange[0],d.valueRange[1]];else{c=b[e];for(var g=Infinity,f=-Infinity,h=0;h<c.length;h++)g=Math.min(a[c[h]][0],g),f=Math.max(a[c[h]][1],
f);d.includeZero&&0<g&&(g=0);h=f-g;0==h&&(h=f);c=f+0.1*h;h=g-0.1*h;this.attr_("avoidMinZero")||(0>h&&0<=g&&(h=0),0<c&&0>=f&&(c=0));this.attr_("includeZero")&&(0>f&&(c=0),0<g&&(h=0));d.computedValueRange=[h,c]}if(0==e||d.independentTicks)d.ticks=Dygraph.numericTicks(d.computedValueRange[0],d.computedValueRange[1],this,d);else{g=this.axes_[0];f=g.ticks;c=g.computedValueRange[1]-g.computedValueRange[0];for(var h=d.computedValueRange[1]-d.computedValueRange[0],j=[],e=0;e<f.length;e++)j.push(d.computedValueRange[0]+
(f[e].v-g.computedValueRange[0])/c*h);d.ticks=Dygraph.numericTicks(d.computedValueRange[0],d.computedValueRange[1],this,d,j)}}return[this.axes_,this.seriesToAxisMap_]};
Dygraph.prototype.rollingAverage=function(a,b){if(2>a.length)return a;b=Math.min(b,a.length-1);var c=[],e=this.attr_("sigma");if(this.fractions_)for(var d=0,g=0,f=0;f<a.length;f++){d+=a[f][1][0];g+=a[f][1][1];0<=f-b&&(d-=a[f-b][1][0],g-=a[f-b][1][1]);var h=a[f][0],j=g?d/g:0;if(this.attr_("errorBars"))if(this.wilsonInterval_)if(g){var m=0>j?0:j,k=g,j=e*Math.sqrt(m*(1-m)/k+e*e/(4*k*k)),n=1+e*e/g,k=(m+e*e/(2*g)-j)/n,j=(m+e*e/(2*g)+j)/n;c[f]=[h,[100*m,100*(m-k),100*(j-m)]]}else c[f]=[h,[0,0,0]];else k=
g?e*Math.sqrt(j*(1-j)/g):1,c[f]=[h,[100*j,100*k,100*k]];else c[f]=[h,100*j]}else if(this.attr_("customBars"))for(f=g=j=e=k=0;f<a.length;f++)h=a[f][1],d=h[1],c[f]=[a[f][0],[d,d-h[0],h[2]-d]],null!=d&&!isNaN(d)&&(k+=h[0],e+=d,j+=h[2],g+=1),0<=f-b&&(d=a[f-b],null!=d[1][1]&&!isNaN(d[1][1])&&(k-=d[1][0],e-=d[1][1],j-=d[1][2],g-=1)),c[f]=[a[f][0],[1*e/g,1*(e-k)/g,1*(j-e)/g]];else if(Math.min(b-1,a.length-2),this.attr_("errorBars"))for(f=0;f<a.length;f++){h=k=g=0;for(j=Math.max(0,f-b+1);j<f+1;j++)d=a[j][1][0],
null==d||isNaN(d)||(h++,g+=a[j][1][0],k+=Math.pow(a[j][1][1],2));h?(k=Math.sqrt(k)/h,c[f]=[a[f][0],[g/h,e*k,e*k]]):c[f]=[a[f][0],[null,null,null]]}else{if(1==b)return a;for(f=0;f<a.length;f++){h=g=0;for(j=Math.max(0,f-b+1);j<f+1;j++)d=a[j][1],null==d||isNaN(d)||(h++,g+=a[j][1]);c[f]=h?[a[f][0],g/h]:[a[f][0],null]}}return c};
Dygraph.dateParser=function(a,b){var c;if(-1!=a.search("-")){for(c=a.replace("-","/","g");-1!=c.search("-");)c=c.replace("-","/");c=Date.parse(c)}else 8==a.length?(c=a.substr(0,4)+"/"+a.substr(4,2)+"/"+a.substr(6,2),c=Date.parse(c)):c=Date.parse(a);(!c||isNaN(c))&&b.error("Couldn't parse "+a+" as a date");return c};
Dygraph.prototype.detectTypeFromString_=function(a){var b=!1;0<=a.indexOf("-")||0<=a.indexOf("/")||isNaN(parseFloat(a))?b=!0:8==a.length&&("19700101"<a&&"20371231">a)&&(b=!0);b?(this.attrs_.xValueFormatter=Dygraph.dateString_,this.attrs_.xValueParser=Dygraph.dateParser,this.attrs_.xTicker=Dygraph.dateTicker,this.attrs_.xAxisLabelFormatter=Dygraph.dateAxisFormatter):(this.attrs_.xValueFormatter=function(a){return a},this.attrs_.xValueParser=function(a){return parseFloat(a)},this.attrs_.xTicker=Dygraph.numericTicks,
this.attrs_.xAxisLabelFormatter=this.attrs_.xValueFormatter)};
Dygraph.prototype.parseCSV_=function(a){var b=[];a=a.split("\n");var c=this.attr_("delimiter");-1==a[0].indexOf(c)&&0<=a[0].indexOf("\t")&&(c="\t");var e=0;this.labelsFromCSV_&&(e=1,this.attrs_.labels=a[0].split(c));for(var d=function(a){a=parseFloat(a);return isNaN(a)?null:a},g,f=!1,h=this.attr_("labels").length,j=!1;e<a.length;e++){var m=a[e];if(0!=m.length&&"#"!=m[0]){var k=m.split(c);if(!(2>k.length)){var n=[];f||(this.detectTypeFromString_(k[0]),g=this.attr_("xValueParser"),f=!0);n[0]=g(k[0],
this);if(this.fractions_)for(var l=1;l<k.length;l++){var p=k[l].split("/");n[l]=[d(p[0]),d(p[1])]}else if(this.attr_("errorBars"))for(l=1;l<k.length;l+=2)n[(l+1)/2]=[d(k[l]),d(k[l+1])];else if(this.attr_("customBars"))for(l=1;l<k.length;l++)p=k[l].split(";"),n[l]=[d(p[0]),d(p[1]),d(p[2])];else for(l=1;l<k.length;l++)n[l]=d(k[l]);0<b.length&&n[0]<b[b.length-1][0]&&(j=!0);b.push(n);n.length!=h&&this.error("Number of columns in line "+e+" ("+n.length+") does not agree with number of labels ("+h+") "+
m)}}}j&&(this.warn("CSV is out of order; order it correctly to speed loading."),b.sort(function(a,b){return a[0]-b[0]}));return b};
Dygraph.prototype.parseArray_=function(a){if(0==a.length)return this.error("Can't plot empty data set"),null;if(0==a[0].length)return this.error("Data set cannot contain an empty row"),null;if(null==this.attr_("labels")){this.warn("Using default labels. Set labels explicitly via 'labels' in the options parameter");this.attrs_.labels=["X"];for(var b=1;b<a[0].length;b++)this.attrs_.labels.push("Y"+b)}if(Dygraph.isDateLike(a[0][0])){this.attrs_.xValueFormatter=Dygraph.dateString_;this.attrs_.xAxisLabelFormatter=
Dygraph.dateAxisFormatter;this.attrs_.xTicker=Dygraph.dateTicker;for(var c=Dygraph.clone(a),b=0;b<a.length;b++){if(0==c[b].length)return this.error("Row "+(1+b)+" of data is empty"),null;if(null==c[b][0]||"function"!=typeof c[b][0].getTime||isNaN(c[b][0].getTime()))return this.error("x value in row "+(1+b)+" is not a Date"),null;c[b][0]=c[b][0].getTime()}return c}this.attrs_.xValueFormatter=function(a){return a};this.attrs_.xTicker=Dygraph.numericTicks;return a};
Dygraph.prototype.parseDataTable_=function(a){var b=a.getNumberOfColumns(),c=a.getNumberOfRows(),e=a.getColumnType(0);if("date"==e||"datetime"==e)this.attrs_.xValueFormatter=Dygraph.dateString_,this.attrs_.xValueParser=Dygraph.dateParser,this.attrs_.xTicker=Dygraph.dateTicker,this.attrs_.xAxisLabelFormatter=Dygraph.dateAxisFormatter;else if("number"==e)this.attrs_.xValueFormatter=function(a){return a},this.attrs_.xValueParser=function(a){return parseFloat(a)},this.attrs_.xTicker=Dygraph.numericTicks,
this.attrs_.xAxisLabelFormatter=this.attrs_.xValueFormatter;else return this.error("only 'date', 'datetime' and 'number' types are supported for column 1 of DataTable input (Got '"+e+"')"),null;for(var d=[],g={},f=!1,h=1;h<b;h++){var j=a.getColumnType(h);"number"==j?d.push(h):"string"==j&&this.attr_("displayAnnotations")?(f=d[d.length-1],g.hasOwnProperty(f)?g[f].push(h):g[f]=[h],f=!0):this.error("Only 'number' is supported as a dependent type with Gviz. 'string' is only supported if displayAnnotations is true")}b=
[a.getColumnLabel(0)];for(h=0;h<d.length;h++)b.push(a.getColumnLabel(d[h])),this.attr_("errorBars")&&(h+=1);this.attrs_.labels=b;for(var b=b.length,j=[],m=!1,k=[],h=0;h<c;h++){var n=[];if("undefined"===typeof a.getValue(h,0)||null===a.getValue(h,0))this.warn("Ignoring row "+h+" of DataTable because of undefined or null first column.");else{"date"==e||"datetime"==e?n.push(a.getValue(h,0).getTime()):n.push(a.getValue(h,0));if(this.attr_("errorBars"))for(l=0;l<b-1;l++)n.push([a.getValue(h,1+2*l),a.getValue(h,
2+2*l)]);else for(var l=0;l<d.length;l++){var p=d[l];n.push(a.getValue(h,p));if(f&&g.hasOwnProperty(p)&&null!=a.getValue(h,g[p][0])){var q={};q.series=a.getColumnLabel(p);q.xval=n[0];q.shortText=String.fromCharCode(65+k.length);q.text="";for(var s=0;s<g[p].length;s++)s&&(q.text+="\n"),q.text+=a.getValue(h,g[p][s]);k.push(q)}}0<j.length&&n[0]<j[j.length-1][0]&&(m=!0);j.push(n)}}m&&(this.warn("DataTable is out of order; order it correctly to speed loading."),j.sort(function(a,b){return a[0]-b[0]}));
this.rawData_=j;0<k.length&&this.setAnnotations(k,!0)};Dygraph.update=function(a,b){if("undefined"!=typeof b&&null!==b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};Dygraph.isArrayLike=function(a){var b=typeof a;return"object"!=b&&!("function"==b&&"function"==typeof a.item)||null===a||"number"!=typeof a.length||3===a.nodeType?!1:!0};Dygraph.isDateLike=function(a){return"object"!=typeof a||null===a||"function"!=typeof a.getTime?!1:!0};
Dygraph.clone=function(a){for(var b=[],c=0;c<a.length;c++)Dygraph.isArrayLike(a[c])?b.push(Dygraph.clone(a[c])):b.push(a[c]);return b};
Dygraph.prototype.start_=function(){if("function"==typeof this.file_)this.loadedEvent_(this.file_());else if(Dygraph.isArrayLike(this.file_))this.rawData_=this.parseArray_(this.file_),this.predraw_();else if("object"==typeof this.file_&&"function"==typeof this.file_.getColumnRange)this.parseDataTable_(this.file_),this.predraw_();else if("string"==typeof this.file_)if(0<=this.file_.indexOf("\n"))this.loadedEvent_(this.file_);else{var a=new XMLHttpRequest,b=this;a.onreadystatechange=function(){4==a.readyState&&
200==a.status&&b.loadedEvent_(a.responseText)};a.open("GET",this.file_,!0);a.send(null)}else this.error("Unknown data format: "+typeof this.file_)};
Dygraph.prototype.updateOptions=function(a){"rollPeriod"in a&&(this.rollPeriod_=a.rollPeriod);"dateWindow"in a&&(this.dateWindow_=a.dateWindow);Dygraph.update(this.user_attrs_,a);Dygraph.update(this.renderOptions_,a);this.labelsFromCSV_=null==this.attr_("labels");this.layout_.updateOptions({errorBars:this.attr_("errorBars")});a.file?(this.file_=a.file,this.start_()):this.predraw_()};
Dygraph.prototype.resize=function(a,b){this.resize_lock||(this.resize_lock=!0,null===a!=(null===b)&&(this.warn("Dygraph.resize() should be called with zero parameters or two non-NULL parameters. Pretending it was zero."),a=b=null),this.maindiv_.innerHTML="",this.attrs_.labelsDiv=null,a?(this.maindiv_.style.width=a+"px",this.maindiv_.style.height=b+"px",this.width_=a,this.height_=b):(this.width_=this.maindiv_.offsetWidth,this.height_=this.maindiv_.offsetHeight),this.createInterface_(),this.predraw_(),
this.resize_lock=!1)};Dygraph.prototype.adjustRoll=function(a){this.rollPeriod_=a;this.predraw_()};Dygraph.prototype.visibility=function(){for(this.attr_("visibility")||(this.attrs_.visibility=[]);this.attr_("visibility").length<this.rawData_[0].length-1;)this.attr_("visibility").push(!0);return this.attr_("visibility")};Dygraph.prototype.setVisibility=function(a,b){var c=this.visibility();0>a||a>=c.length?this.warn("invalid series number in setVisibility: "+a):(c[a]=b,this.predraw_())};
Dygraph.prototype.setAnnotations=function(a,b){Dygraph.addAnnotationRule();this.annotations_=a;this.layout_.setAnnotations(this.annotations_);b||this.predraw_()};Dygraph.prototype.annotations=function(){return this.annotations_};Dygraph.prototype.indexFromSetName=function(a){for(var b=this.attr_("labels"),c=0;c<b.length;c++)if(b[c]==a)return c;return null};
Dygraph.addAnnotationRule=function(){if(!Dygraph.addedAnnotationCSS){var a=document.createElement("style");a.type="text/css";document.getElementsByTagName("head")[0].appendChild(a);for(a=0;a<document.styleSheets.length;a++)if(!document.styleSheets[a].disabled){var b=document.styleSheets[a];try{b.insertRule?b.insertRule(".dygraphDefaultAnnotation { border: 1px solid black; background-color: white; text-align: center; }",b.cssRules?b.cssRules.length:0):b.addRule&&b.addRule(".dygraphDefaultAnnotation",
"border: 1px solid black; background-color: white; text-align: center;");Dygraph.addedAnnotationCSS=!0;return}catch(c){}}this.warn("Unable to add default annotation CSS rule; display may be off.")}};Dygraph.createCanvas=function(){var a=document.createElement("canvas");(isIE=/MSIE/.test(navigator.userAgent)&&!window.opera)&&"undefined"!=typeof G_vmlCanvasManager&&(a=G_vmlCanvasManager.initElement(a));return a};Dygraph.GVizChart=function(a){this.container=a};
Dygraph.GVizChart.prototype.draw=function(a,b){this.container.innerHTML="";"undefined"!=typeof this.date_graph&&this.date_graph.destroy();this.date_graph=new Dygraph(this.container,a,b)};Dygraph.GVizChart.prototype.setSelection=function(a){var b=!1;a.length&&(b=a[0].row);this.date_graph.setSelection(b)};Dygraph.GVizChart.prototype.getSelection=function(){var a=[],b=this.date_graph.getSelection();if(0>b)return a;col=1;for(var c in this.date_graph.layout_.datasets)a.push({row:b,column:col}),col++;return a};
DateGraph=Dygraph;
