var chartData=null,lineChart=null,sliderCharti=null,barChart=null;function formatDate(c){return""+(10>c.getDate()?"0":"")+c.getDate()+"-"+(9>c.getMonth()?"0":"")+(c.getMonth()+1)+"-"+c.getFullYear()}function formatTime(c){return""+(10>c.getHours()?"0":"")+c.getHours()+":"+(10>c.getMinutes()?"0":"")+c.getMinutes()}function parseDate(c,d){var b=c.split("-"),e=d.split(":");return new Date(b[2],b[1]-1,b[0],e[0],e[1],0,0)}
function getStyleBySelector(c){var d=document.styleSheets,b,e,f,g,h,k=void 0==d[0].cssRules;for(g=d.length-1;0<=g;g--){b=k?d[g].rules:d[g].cssRules;f=findStyle(b,c);if(null!=f)return f;b=k?d[g].imports:b;for(h=0;h<b.length;h++){if(void 0!=b[h].rules)e=b[h].rules;else if(void 0!=b[h].styleSheet)e=b[h].styleSheet.cssRules;else if(void 0!=document.cookie&&0<=document.cookie.indexOf("mysmartgrid_cookiecontrol"))window.location="/webbrowser";else return null;f=findStyle(e,c);if(null!=f)return f}}return null}
function findStyle(c,d){var b,e;for(b=0;b<c.length;b++)if(e=c[b],e.selectorText&&e.selectorText.toLowerCase()==d)return e.style;return null}function percentToPx(c,d){return-1<c.indexOf("%")?parseInt(c.replace("%",""))*d/100:c.replace("px","")}function isMobile(){return 600>document.body.clientWidth}function hideZero(c){return 0==c?"":c.toFixed(2)}
function updateLineChartForm(c){var d=document.getElementById("logger-linechart-form");if(d){var b=Math.round(c.yAxisRange(0)[0]),e=Math.round(c.yAxisRange(0)[1]);0==e&&0==b&&(e=b="");d.elements.yvalue1.value=b;d.elements.yvalue2.value=e;b=new Date(Math.round(c.xAxisRange(0)[0]));d.elements.xvalue1date.value=formatDate(b);d.elements.xvalue1time.value=formatTime(b);b=new Date(Math.round(c.xAxisRange(0)[1]));d.elements.xvalue2date.value=formatDate(b);d.elements.xvalue2time.value=formatTime(b)}refreshLineAnnotations();
updateLineLegend(c)}function submitLineChartForm(c){var d=document.getElementById("logger-linechart-form");c&&(d.elements.yvalue1.value="",d.elements.yvalue2.value="");d.submit()}function enableFilledGraph(){document.getElementById("logger-linechart-form").elements.filled_graph.checked=1}
function submitBarChartForm(c){var d=document.getElementById("logger-barchart-form"),b=findCheckBoxes(d,"selected_meters"),e=!1,f=!1;0<b.length&&(f=!0,e=isAnyOptionChecked(b));if(!f||e)b=findCheckBoxes(d,"selected_sensor_types"),f=!1,0<b.length&&(f=!0,e=isAnyOptionChecked(b));!f||e?d.submit():c.checked=!0}function isAnyOptionChecked(c){for(var d=!1,b=0;b<c.length;b++)if(c[b].checked){d=!0;break}return d}
function findCheckBoxes(c,d){for(var b=[],e=0,f=0;f<c.elements.length;f++)0==c.elements[f].name.indexOf(d,0)&&(b[e++]=c.elements[f]);return b}function removeLineSeries(c,d,b,e,f,g){c=lineChart.visibility();isLastVisibleLine(d,c)||(document.getElementById(f).rows[d+1].style.display="none",setLineVisibility(d,!1),document.getElementById("logger-linechart-form"),jQuery.get("/logger/remove/sensor/"+e+"/"+g))}
function hideLineSeries(c,d,b,e,f,g,h){c=lineChart.visibility();isLastVisibleLine(d,c)||((c=!c[d])?(g=f,f="visible"):f="hidden",document.getElementById("hide-legend-row"+d).innerHTML=g,setLineVisibility(d,c),document.getElementById("max"+d).style.visibility=f,document.getElementById("min"+d).style.visibility=f,document.getElementById("avg"+d).style.visibility=f,document.getElementById("last"+d).style.visibility=f,jQuery.get("/logger/hide/sensor/"+e+"/"+h))}
function isLastVisibleLine(c,d){for(var b=0,e=0;e<d.length;e++)b+=d[e]?1:0;return d[c]&&1==b}function setLineVisibility(c,d){lineChart.setVisibility(c,d);sliderChart&&sliderChart.setVisibility(c,d)}function updateSmoothingLevel(c,d){var b=document.getElementById(c),e=1*b.value+d,e=1>e?1:e;b.value=e;lineChart.setAnnotations([]);lineChart.updateOptions({rollPeriod:e});sliderChart&&sliderChart.updateOptions({rollPeriod:e});jQuery.get("/logger/setvariable/smoothing_level/"+e);return!0}
function updateLineChart(c,d){lineChart.updateOptions({dateWindow:[c,d]});sliderChart&&sliderChart.updateOptions({dateWindow:null});updateLineChartForm(lineChart)}function updateSliderChart(){sliderChart.updateOptions({dateWindow:sliderChart.xAxisRange()});updateLineChartForm(lineChart)}function expandLineChart(){lineChart.updateOptions({dateWindow:null});lineChart.updateOptions({valueRange:null});updateSliderChart()}
function slideLineChart(c,d){var b=lineChart.xAxisRange(0)[0],e=lineChart.xAxisRange(0)[1],b=(e-b)/2;lineChart.updateOptions({dateWindow:[d-b,d+b]});sliderChart.updateOptions({dateWindow:sliderChart.xAxisRange()});updateLineChartForm(lineChart)}function highlightLineChart(c,d,b){var e=lineChart.xAxisRange(0)[0],f=lineChart.xAxisRange(0)[1],g=b.yAxisRange(0)[0],h=b.yAxisRange(0)[1],e=b.toDomCoords(e,0)[0];b=b.toDomCoords(f,0)[0]-e;c.fillStyle="#a5d2d9";c.fillRect(e,d.y,b,h-g+100)}
function updateLineLegend(c){for(var d=c.xAxisRange(0)[0],b=c.xAxisRange(0)[1],e=c.visibility(),f=1;f<c.numColumns();f++){var g=Number.MIN_VALUE,h=Number.MAX_VALUE,k=0,p=0,m=null;if(e[f-1])for(var j=0;j<c.numRows();j++){var l=c.getValue(j,0);l>=d&&l<=b&&(m=l=(l=c.getValue(j,f))?l:0,g=l>g?l:g,h=l<h?l:h,0!=l&&(k+=l,p++))}g=g==Number.MIN_VALUE?null:g;h=h==Number.MAX_VALUE?null:h;avg=0<p?k/p:null;updateLineLegendValue("max",f,g);updateLineLegendValue("min",f,h);updateLineLegendValue("avg",f,avg);updateLineLegendValue("last",
f,m);updateLineLegendValue("sum",f,k)}}function updateLineLegendValue(c,d,b){if(c=document.getElementById(c+--d))b&&!isNaN(b-0)?(d=Math.abs(b),b=0.01<=d?b.toFixed(2):0.001<=d?b.toFixed(3):b,c.innerHTML=0==d?"":0.001>d?"0.000...":b):c.innerHTML=""}var annotationDivs={};
function addLineAnnotation(c,d){var b=d.name.substring(1)-1,e="annotation"+b+""+d.xval,f=(d.xval-d.xval%36E5)/1E3,g=new Date(d.xval),h=(g.getTime()-g.getTime()%1E3)/1E3,k=d.yval.toFixed(2),p=d.name+": "+formatDate(g)+" - "+k,m=50*(""+k).length/6,j=15,g="",l=getAppliances(b,h);l&&(g+=l,m+=45*(l.length/100),j=30);if(b=getWeather(b,f))g+=b,m+=75,j=30;h={series:d.name,x:h,shortText:k,text:p,width:m,height:j,cssClass:"point-annotation "+e,clickHandler:function(b,c,d){removeLineAnnotation(d,e)}};f=lineChart.annotations();
f.push(h);lineChart.setAnnotations(f);h=findAnnotationDiv(e);if(b||l)h.innerHTML='<span class="point-annotation">'+k+"</span>"+g;annotationDivs[e]=h.innerHTML;refreshLineAnnotations()}function refreshLineAnnotations(){for(id in annotationDivs){var c=findAnnotationDiv(id);c&&(c.innerHTML=annotationDivs[id])}}function removeLineAnnotation(c,d){for(var b=[],e=c.annotations(),f=0;f<e.length;f++)0>e[f].cssClass.indexOf(d)&&b.push(e[f]);c.setAnnotations(b);refreshLineAnnotations()}
function findAnnotationDiv(c){for(var d=document.getElementsByTagName("div"),b=0;b<d.length;b++){var e=d[b];if(-1!=e.className.indexOf(c))return e}return null}function getAppliances(c,d){var b=[],e=lineChart.fileURL.substring(lineChart.fileURL.lastIndexOf("/")+1);jQuery.ajax({async:!1,url:"/logger/getappliances/"+e,success:function(c){b=c}});e="";for(a in b[c])0<parseInt(b[c][a][d])&&(e+='<img class="point-annotation" src="/sites/all/modules/logger/img/appliances/icon-'+a+'.jpg"/>');return e}
function getWeather(c,d){for(var b=lineChart.weather,e=0;e<b.length;e++)if(b[e][0]==c)for(var f=0;f<b[e][1].length;f++)if(b[e][1][f][0]==d)return'<span class="point-annotation">&nbsp;&nbsp;('+b[e][1][f][2]+'\u00b0)</span><img class="point-annotation" src="/sites/all/modules/logger/img/weather/icon-'+b[e][1][f][1]+'.jpg"/>';return null}function downloadChartData(c){null==chartData&&jQuery.ajax({url:"/"+c,async:!1,success:function(c){chartData=c}});return chartData}
function createLineChart(c,d,b,e){var f=document.getElementById(c),g=getStyleBySelector("div."+f.className);b.width=percentToPx(g.width,f.clientWidth);b.height=percentToPx(g.height);b.axisLabelFontSize=g.fontSize.replace("px","");b.yAxisLabelWidth=4*b.axisLabelFontSize;b=new Dygraph(f,downloadChartData(d),b);b.weather=e;b.fileURL=d;storeChart(c,b);return b}
function createBarChart(c,d,b,e,f,g,h,k){for(var p=0<h.length,m=b.length,j=1/((p?Math.max.apply(null,h)+1:d.length)+1),l,t=[m],n=0;n<m;n++)l=n+(p?0:Math.floor((d.length-1)/2)*j),t[n]=[l,b[n]];var r=[d.length];for(b=0;b<d.length;b++){for(var n=[m],s=h[b],q=0;q<m;q++)l=q+j*(p?s:b),n[q]=[l,d[b][q]];r[b]={data:n,stack:p?h[b]:null}}var u={colors:e,series:{bars:{show:!0,barWidth:j,lineWidth:0,fill:1,align:"center"}},xaxis:{min:-1*j,max:m-j,ticks:t},grid:{clickable:!0},yaxis:{autoscaleMargin:0.05,tickFormatter:function(b){return k?
b.toFixed(0)+"%":b.toFixed(1)}}};d={};d.id=c;d.data=r;d.options=u;d.plot=function(){var b=jQuery.plot(jQuery("#"+c),r,u);showBarDataLabels(b,h,f,j,15);showBarDataLabels(b,h,g,j,-5)};d.plot();storeChart(c,d);return d}function storeChart(c,d){"lineChart"==c?(lineChart=d,barChart=sliderChart=null):"sliderChart"==c?(sliderChart=d,chartData=barChart=null):"barChart"==c&&(barChart=d,chartData=sliderChart=lineChart=null)}
function getChart(c){return"lineChart"==c?lineChart:"sliderChart"==c?sliderChart:"barChart"==c?barChart:null}
function showBarDataLabels(c,d,b,e,f){if(0!=b.length)for(var g=c.getData(),h=0<d.length,k=c.pointOffset({x:0,y:0}),p=k.top,m=createBiArray(20,20,f),j=0;j<g.length;j++)void 0!=b[j]&&jQuery.each(g[j].data,function(f,g){var n=g[0];if(0<=n){var r=g[1];if(!(0>=r)){var s=h?d[j]:j,q=Math.round(n-e*s);k=c.pointOffset({x:n,y:r});n=p-k.top;k.top-=m[s][q];15>n&&(k.top+=n-15);h&&(m[s][q]+=n);showDataLabel(c,k,e,b[j][q])}}})}
function showDataLabel(c,d,b,e){if(null!=e){"number"==typeof e&&(e=e.toFixed(1E3>e?2:0),0==e&&(e+="..."));var f=getStyleBySelector("p.chart-label"),f=parseInt(f.fontSize.replace("px",""));0.3<b&&(f+=2);d={position:"absolute",left:d.left-25,top:d.top,display:"none"};jQuery('<div style="font-size: '+f+'px; width: 50px; height: 15px; text-align: center;">'+e+"</div>").css(d).appendTo(c.getPlaceholder()).fadeIn("slow")}}
function createBiArray(c,d,b){for(var e=Array(c),f=0;f<c;f++){e[f]=Array(d);for(var g=0;g<d;g++)e[f][g]=b}return e}function setSeriesColor(c,d,b){b="#"+b;barChart&&(barChart.options.colors[d]=b,barChart.plot());lineChart&&updateDygraphColors();jQuery.get("/logger/setvariable/series_color_"+c+"_"+d+"/"+escape(b));return!0}
function syncColorPickers(c,d){for(var b=document.getElementsByClassName("color"),e=0;e<b.length;e++)0<b[e].className.indexOf("series_color"+c)&&(b[e].style.background="#"+d,b[e].style.color="transparent",b[e].value=d);return!0}function updateDygraphColors(){for(var c=lineChart.getColors(),d=lineChart.visibility(),b=0;b<d.length;b++){var e=document.getElementById("series_color"+b);e&&(c[b]="#"+e.value)}lineChart.updateOptions({colors:c});sliderChart&&sliderChart.updateOptions({colors:c})}
function resizeCharts(){isMobile()&&(resizeLineChart("lineChart"),resizeLineChart("sliderChart"),resizeBarChart())}function resizeLineChart(c){var d=getChart(c);if(d){var b=400<document.body.clientWidth;c=document.getElementById(c);c=getStyleBySelector("div."+c.className).height.replace("px","");d.resize(b?460:295,c)}}function resizeBarChart(){barChart&&barChart.plot()}
function resizeLegend(c,d,b){if(isMobile()&&(c=document.getElementById(c))){var e=400<document.body.clientWidth?"table-cell":"none";d=d?d:3;b=b?b:c.rows[0].cells.length-1;for(var f=0;f<c.rows.length;f++)for(var g=c.rows[f].cells,h=d;h<b;h++)g[h].style.display=e}};