var chartData=null,lineChart=null,sliderCharti=null,barChart=null;function formatDate(b){return""+(10>b.getDate()?"0":"")+b.getDate()+"-"+(9>b.getMonth()?"0":"")+(b.getMonth()+1)+"-"+b.getFullYear()}function formatTime(b){return""+(10>b.getHours()?"0":"")+b.getHours()+":"+(10>b.getMinutes()?"0":"")+b.getMinutes()}function parseDate(b,d){var c=b.split("-"),e=d.split(":");return new Date(c[2],c[1]-1,c[0],e[0],e[1],0,0)}
function getStyleBySelector(b){var d=document.styleSheets,c,e,f,g,h,l=void 0==d[0].cssRules;for(g=d.length-1;0<=g;g--){c=l?d[g].rules:d[g].cssRules;f=findStyle(c,b);if(null!=f)return f;c=l?d[g].imports:c;for(h=0;h<c.length;h++){if(void 0!=c[h].rules)e=c[h].rules;else if(void 0!=c[h].styleSheet)e=c[h].styleSheet.cssRules;else if(void 0!=document.cookie&&0<=document.cookie.indexOf("mysmartgrid_cookiecontrol"))window.location="/webbrowser";else return null;f=findStyle(e,b);if(null!=f)return f}}return null}
function findStyle(b,d){var c,e;for(c=0;c<b.length;c++)if(e=b[c],e.selectorText&&e.selectorText.toLowerCase()==d)return e.style;return null}function percentToPx(b,d){return-1<b.indexOf("%")?parseInt(b.replace("%",""))*d/100:b.replace("px","")}function formatYValue(b){if(null==b||isNaN(b-0))return"";var d=Math.abs(b);b=0.01<=d?b.toFixed(2):0.001<=d?b.toFixed(3):b;return 0<d&&0.001>d?"0.000...":b}
function updateLineChartForm(b){var d=document.getElementById("logger-linechart-form");if(d){var c=Math.round(b.yAxisRange(0)[0]),e=Math.round(b.yAxisRange(0)[1]);0==e&&0==c&&(e=c="");d.elements.yvalue1.value=c;d.elements.yvalue2.value=e;c=new Date(Math.round(b.xAxisRange(0)[0]));d.elements.xvalue1date.value=formatDate(c);d.elements.xvalue1time.value=formatTime(c);c=new Date(Math.round(b.xAxisRange(0)[1]));d.elements.xvalue2date.value=formatDate(c);d.elements.xvalue2time.value=formatTime(c)}refreshLineAnnotations();
updateLineLegend(b)}function submitLineChartForm(b){var d=document.getElementById("logger-linechart-form");b&&(d.elements.yvalue1.value="",d.elements.yvalue2.value="");d.submit()}function enableFilledGraph(){document.getElementById("logger-linechart-form").elements.filled_graph.checked=1}
function submitBarChartForm(b){var d=document.getElementById("logger-barchart-form"),c=findCheckBoxes(d,"selected_meters"),e=!1,f=!1;0<c.length&&(f=!0,e=isAnyOptionChecked(c));if(!f||e)c=findCheckBoxes(d,"selected_sensor_types"),f=!1,0<c.length&&(f=!0,e=isAnyOptionChecked(c));!f||e?d.submit():b.checked=!0}function isAnyOptionChecked(b){for(var d=!1,c=0;c<b.length;c++)if(b[c].checked){d=!0;break}return d}
function findCheckBoxes(b,d){for(var c=[],e=0,f=0;f<b.elements.length;f++)0==b.elements[f].name.indexOf(d,0)&&(c[e++]=b.elements[f]);return c}function removeLineSeries(b,d,c,e,f,g){b=lineChart.visibility();isLastVisibleLine(d,b)||(document.getElementById(f).rows[d+1].style.display="none",setLineVisibility(d,!1),document.getElementById("logger-linechart-form"),jQuery.get("/logger/remove/sensor/"+e+"/"+g))}
function hideLineSeries(b,d,c,e,f,g,h){b=lineChart.visibility();isLastVisibleLine(d,b)||((b=!b[d])?(g=f,f="visible"):f="hidden",document.getElementById("hide-legend-row"+d).innerHTML=g,setLineVisibility(d,b),document.getElementById("max"+d).style.visibility=f,document.getElementById("min"+d).style.visibility=f,document.getElementById("avg"+d).style.visibility=f,document.getElementById("last"+d).style.visibility=f,jQuery.get("/logger/hide/sensor/"+e+"/"+h))}
function isLastVisibleLine(b,d){for(var c=0,e=0;e<d.length;e++)c+=d[e]?1:0;return d[b]&&1==c}function setLineVisibility(b,d){lineChart.setVisibility(b,d);sliderChart&&sliderChart.setVisibility(b,d)}function updateSmoothingLevel(b,d){var c=document.getElementById(b),e=1*c.value+d,e=1>e?1:e;c.value=e;lineChart.setAnnotations([]);lineChart.updateOptions({rollPeriod:e});sliderChart&&sliderChart.updateOptions({rollPeriod:e});jQuery.get("/logger/setvariable/smoothing_level/"+e);return!0}
function updateLineChart(b,d,c){lineChart.updateOptions({dateWindow:[b,d]});sliderChart&&sliderChart.updateOptions({dateWindow:null});updateLineChartForm(lineChart)}function updateSliderChart(b,d,c){sliderChart.updateOptions({dateWindow:sliderChart.xAxisRange()});updateLineChartForm(lineChart)}function expandLineChart(){lineChart.updateOptions({dateWindow:null});lineChart.updateOptions({valueRange:null});updateSliderChart()}
function slideLineChart(b,d){var c=lineChart.xAxisRange(0)[0],e=lineChart.xAxisRange(0)[1],c=(e-c)/2;lineChart.updateOptions({dateWindow:[d-c,d+c]});sliderChart.updateOptions({dateWindow:sliderChart.xAxisRange()});updateLineChartForm(lineChart)}function highlightLineChart(b,d,c){var e=lineChart.xAxisRange(0)[0],f=lineChart.xAxisRange(0)[1],g=c.yAxisRange(0)[0],h=c.yAxisRange(0)[1],e=c.toDomCoords(e,0)[0];c=c.toDomCoords(f,0)[0]-e;b.fillStyle="#a5d2d9";b.fillRect(e,d.y,c,h-g+100)}
function updateLineLegend(b){for(var d=b.xAxisRange(0)[0],c=b.xAxisRange(0)[1],e=b.visibility(),f=1;f<b.numColumns();f++){var g=Number.MIN_VALUE,h=Number.MAX_VALUE,l=0,q=0,n=null;if(e[f-1])for(var k=0;k<b.numRows();k++){var m=b.getValue(k,0);m>=d&&m<=c&&(m=b.getValue(k,f),null==m||isNaN(m-0)||(n=m,g=m>g?m:g,h=m<h?m:h,l+=m,q++))}g=g==Number.MIN_VALUE?null:g;h=h==Number.MAX_VALUE?null:h;avg=0<q?l/q:null;updateLineLegendValue("max",f,g);updateLineLegendValue("min",f,h);updateLineLegendValue("avg",f,
avg);updateLineLegendValue("last",f,n);updateLineLegendValue("sum",f,l)}}function updateLineLegendValue(b,d,c){if(b=document.getElementById(b+--d))b.innerHTML=formatYValue(c)}var annotationDivs={};
function addLineAnnotation(b,d){var c=d.name.substring(1)-1,e="annotation"+c+""+d.xval,f=(d.xval-d.xval%36E5)/1E3,g=new Date(d.xval),h=(g.getTime()-g.getTime()%1E3)/1E3,l=d.yval.toFixed(2),q=d.name+": "+formatDate(g)+" - "+l,n=50*(""+l).length/6,k=15,g="",m=getAppliances(c,h);m&&(g+=m,n+=45*(m.length/100),k=30);if(c=getWeather(c,f))g+=c,n+=75,k=30;h={series:d.name,x:h,shortText:l,text:q,width:n,height:k,cssClass:"point-annotation "+e,clickHandler:function(c,b,d,f){removeLineAnnotation(d,e)}};f=lineChart.annotations();
f.push(h);lineChart.setAnnotations(f);h=findAnnotationDiv(e);if(c||m)h.innerHTML='<span class="point-annotation">'+l+"</span>"+g;annotationDivs[e]=h.innerHTML;refreshLineAnnotations()}function refreshLineAnnotations(){for(id in annotationDivs){var b=findAnnotationDiv(id);b&&(b.innerHTML=annotationDivs[id])}}function removeLineAnnotation(b,d){for(var c=[],e=b.annotations(),f=0;f<e.length;f++)0>e[f].cssClass.indexOf(d)&&c.push(e[f]);b.setAnnotations(c);refreshLineAnnotations()}
function findAnnotationDiv(b){for(var d=document.getElementsByTagName("div"),c=0;c<d.length;c++){var e=d[c];if(-1!=e.className.indexOf(b))return e}return null}function getAppliances(b,d){var c=[],e=lineChart.fileURL.substring(lineChart.fileURL.lastIndexOf("/")+1);jQuery.ajax({async:!1,url:"/logger/getappliances/"+e,success:function(b){c=b}});e="";for(a in c[b])0<parseInt(c[b][a][d])&&(e+='<img class="point-annotation" src="/sites/all/modules/logger/img/appliances/icon-'+a+'.jpg"/>');return e}
function getWeather(b,d){for(var c=lineChart.weather,e=0;e<c.length;e++)if(c[e][0]==b)for(var f=0;f<c[e][1].length;f++)if(c[e][1][f][0]==d)return'<span class="point-annotation">&nbsp;&nbsp;('+c[e][1][f][2]+'\u00c2\u00b0)</span><img class="point-annotation" src="/sites/all/modules/logger/img/weather/icon-'+c[e][1][f][1]+'.jpg"/>';return null}function downloadChartData(b){null==chartData&&jQuery.ajax({url:"/"+b,async:!1,success:function(b){chartData=b}});return chartData}
function createLineChart(b,d,c,e){var f=document.getElementById(b),g=getStyleBySelector("div."+f.className);c.width=percentToPx(g.width,f.clientWidth);c.height=percentToPx(g.height);c.axisLabelFontSize=g.fontSize.replace("px","");c.yAxisLabelWidth=4*c.axisLabelFontSize;c=new Dygraph(f,downloadChartData(d),c);c.weather=e;c.fileURL=d;storeChart(b,c);return c}
function createBarChart(b,d,c,e,f,g,h,l){for(var q=0<h.length,n=c.length,k=1/((q?Math.max.apply(null,h)+1:d.length)+1),m,u=[n],p=0;p<n;p++)m=p+(q?0:Math.floor((d.length-1)/2)*k),u[p]=[m,c[p]];var s=[d.length];for(c=0;c<d.length;c++){for(var p=[n],t=h[c],r=0;r<n;r++)m=r+k*(q?t:c),p[r]=[m,d[c][r]];s[c]={data:p,stack:q?h[c]:null}}var v={colors:e,series:{bars:{show:!0,barWidth:k,lineWidth:0,fill:1,align:"center"}},xaxis:{min:-1*k,max:n-k,ticks:u},grid:{clickable:!0},yaxis:{autoscaleMargin:0.05,tickFormatter:function(b,
c){return l?b.toFixed(0)+"%":b.toFixed(1)}}};d={};d.id=b;d.data=s;d.options=v;d.plot=function(){var c=jQuery.plot(jQuery("#"+b),s,v);showBarDataLabels(c,h,f,k,15);showBarDataLabels(c,h,g,k,-5)};d.plot();storeChart(b,d);return d}function storeChart(b,d){"lineChart"==b?(lineChart=d,barChart=sliderChart=null):"sliderChart"==b?(sliderChart=d,chartData=barChart=null):"barChart"==b&&(barChart=d,chartData=sliderChart=lineChart=null)}
function getChart(b){return"lineChart"==b?lineChart:"sliderChart"==b?sliderChart:"barChart"==b?barChart:null}
function showBarDataLabels(b,d,c,e,f){if(0!=c.length)for(var g=b.getData(),h=0<d.length,l=b.pointOffset({x:0,y:0}),q=l.top,n=createBiArray(20,20,f),k=0;k<g.length;k++)void 0!=c[k]&&jQuery.each(g[k].data,function(f,g){var p=g[0];if(0<=p){var s=g[1];if(!(0>=s)){var t=h?d[k]:k,r=Math.round(p-e*t);l=b.pointOffset({x:p,y:s});p=q-l.top;l.top-=n[t][r];15>p&&(l.top+=p-15);h&&(n[t][r]+=p);showDataLabel(b,l,e,c[k][r])}}})}
function showDataLabel(b,d,c,e){if(null!=e){"number"==typeof e&&(e=e.toFixed(1E3>e?2:0),0==e&&(e+="..."));var f=getStyleBySelector("p.chart-label"),f=parseInt(f.fontSize.replace("px",""));0.3<c&&(f+=2);d={position:"absolute",left:d.left-25,top:d.top,display:"none"};jQuery('<div style="font-size: '+f+'px; width: 50px; height: 15px; text-align: center;">'+e+"</div>").css(d).appendTo(b.getPlaceholder()).fadeIn("slow")}}
function createBiArray(b,d,c){for(var e=Array(b),f=0;f<b;f++){e[f]=Array(d);for(var g=0;g<d;g++)e[f][g]=c}return e}function setSeriesColor(b,d,c){c="#"+c;barChart&&(barChart.options.colors[d]=c,barChart.plot());lineChart&&updateDygraphColors();jQuery.get("/logger/setvariable/series_color_"+b+"_"+d+"/"+escape(c));return!0}
function syncColorPickers(b,d){for(var c=document.getElementsByClassName("color"),e=0;e<c.length;e++)0<c[e].className.indexOf("series_color"+b)&&(c[e].style.background="#"+d,c[e].style.color="transparent",c[e].value=d);return!0}function updateDygraphColors(){for(var b=lineChart.getColors(),d=lineChart.visibility(),c=0;c<d.length;c++){var e=document.getElementById("series_color"+c);e&&(b[c]="#"+e.value)}lineChart.updateOptions({colors:b});sliderChart&&sliderChart.updateOptions({colors:b})}
function resizeCharts(){isMobile()&&(resizeLineChart("lineChart"),resizeLineChart("sliderChart"),resizeBarChart())}function resizeLineChart(b){var d=getChart(b);if(d){var c=400<document.body.clientWidth;b=document.getElementById(b);b=getStyleBySelector("div."+b.className).height.replace("px","");d.resize(c?460:295,b)}}function resizeBarChart(){barChart&&barChart.plot()};