<?php

/**
 * This module manages Flukso devices' event notifications.
 *
 * Copyright (c) 2010 Fraunhofer Institut ITWM (www.itwm.fraunhofer.de)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

define('NO_COMMUNICATION_EVENT_ID',      1);
define('CORRUPTED_MEASUREMENT_EVENT_ID', 2);
define('PEAK_CONSUMPTION_EVENT_ID',      4);
define('BROWNOUT_EVENT_ID',              5);
define('HEARTBEAT_RECEIVED_EVENT_ID',    6);
define('MEASUREMENT_RECEIVED_EVENT_ID',  7);

define('HOUR_UNIT_ID',      2);
define('WATT_HOUR_UNIT_ID', 4);
define('TIMESTAMP_FORMAT', '%d-%m-%Y %H:%i:%s');


function notification_help($path, $arg) {

  $output = '';

  switch ($path) {
    case "admin/help#notification":
      $output = '<p>'.t("Allows the users to manage device event notifications.").'</p>';
      break;
  }

  return $output;
}

function notification_perm() {
  return array('manage notifications');
}

function notification_settings_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}

function notification_menu() {

  $items = array();

  $items['notification/list'] = array(
    'title'             => 'Event Notifications',
    'page callback'     => 'notification_list_page',
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_NORMAL_ITEM
  );

  $items['notification/delete'] = array(
    'title'             => $items['notification/list']['title'],
    'page callback'     => 'notification_delete',
    'page arguments'    => array(2, 3, 4, 5),
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_CALLBACK
  );

  $items['notification/register'] = array(
    'title'             => 'Event Notification Registration',
    'page callback'     => 'notification_registration_page',
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_CALLBACK
  );

  $items['notification/edit'] = array(
    'title'             => 'Event Notification Edition',
    'page callback'     => 'notification_edition_page',
    'page arguments'    => array(2, 3, 4, 5),
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_CALLBACK
  );

  $items['event/log/list'] = array(
    'title'             => 'Device History',
    'page callback'     => 'notification_eventlog_page',
    'page arguments'    => array(3),
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_CALLBACK
  );

  $items['event/log/clear'] = array(
    'title'             => $items['event/log/list']['title'],
    'page callback'     => '_notification_eventlog_clear',
    'page arguments'    => array(3),
    'access arguments'  => array('manage notifications'),
    'type'              => MENU_CALLBACK
  );

  $items['newsletter'] = array(
    'title'             => 'Newsletter',
    'page callback'     => 'notification_newsletter_page',
    'access callback'   => TRUE,
    'type'              => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Event notification deletion callback.
 *
 * @param $device    The monitored device.
 * @param $event_id  The event id.
 * @param $limit_up  The event's threshold.
 * @param $unit_id   The unit id.
 * @return the events list page.
 */
function notification_delete($device, $event_id, $limit_up, $unit_id) {

  _notification_delete($device, $event_id, $limit_up, $unit_id);
  return notification_list_page();
}

/**
 * Builds the event registration page.
 *
 * @return the event registration page.
 */
function notification_registration_page() {
  return drupal_get_form('notification_registration_form');
}

/**
 * Builds the event notification edition page.
 *
 * @param $device    The monitored device.
 * @param $event_id  The event id.
 * @param $limit_up  The event's threshold.
 * @param $unit_id   The unit id.
 * @return the event notification edition page.
 */
function notification_edition_page($device, $event_id, $limit_up, $unit_id) {

  $sql = "
    SELECT
      e.id AS event_id,
      e.name AS event_name,
      n.device AS device,
      d.serial AS serial,
      n.emails AS emails,
      n.min_interval AS min_interval,
      n.limit_up AS limit_up,
      n.unit_id
    FROM
      {event} e,
      {notification} n,
      {logger_devices} d
    WHERE
      d.device = '%s' AND
      d.device = n.device AND
      n.event_id = e.id AND
      e.id = %d AND
      n.limit_up = %f AND
      n.unit_id = %d";

  $notification = db_fetch_object(db_query($sql, $device, $event_id, $limit_up, $unit_id));

  return drupal_get_form('notification_edition_form', $notification);
}

/**
 * Builds the events list page.
 *
 * @return the events list page.
 */
function notification_list_page() {

  $sql = "
    SELECT
      d.serial AS serial,
      e.name AS event_name,
      n.emails AS emails,
      IF(n.last_sent = 0, NULL, FROM_UNIXTIME(n.last_sent + u.timezone, '%s')) AS last_sent,
      n.limit_up AS limit_up,
      un.id AS unit_id,
      un.symbol AS unit,
      d.device AS device,
      e.id AS event_id
    FROM
      {users} u,
      {logger_devices} d,
      {notification} n,
      {event} e,
      {unit} un
    WHERE
      u.uid = d.uid AND
      d.uid = %d AND
      d.device = n.device AND
      n.event_id = e.id AND
      n.unit_id = un.id";

  $headers = array(
    array('data' => t('Device'),         'field' => 'serial',     'sort' => 'ASC'),
    array('data' => t('Event'),          'field' => 'event_name', 'sort' => 'ASC'),
    array('data' => t('Target e-mails'), 'field' => 'emails'),
    array('data' => t('Sent'),           'field' => 'last_sent'),
    array('data' => t('Operation'))
  );

  $sql .= tablesort_sql($headers);

  global $user;
  $result = db_query($sql, TIMESTAMP_FORMAT, $user->uid);

  $rows = array();
  while ($object = db_fetch_array($result)) {

    $event_name = t($object['event_name']) . ($object['unit_id'] == 0? '' :
      '<br>(' . $object['limit_up'] . ' ' . t($object['unit']) . ')');

    $id = $object['device'] . '/' . $object['event_id'] . '/' . $object['limit_up'] . '/' . $object['unit_id'];

    $emails = implode("<br>", _notification_tokenize_emails($object['emails']));

    $row = array();
    $row['serial'] = $object['serial'];
    $row['event_name'] = $event_name;
    $row['emails'] = $emails;
    $row['last_sent'] = $object['last_sent'];
    $row[] = l(t('Remove'), "notification/delete/$id") . '<br>' .
             l(t('Edit'),   "notification/edit/$id");

    $rows[] = $row;
  }

  $caption = '<p>' . l(t('Register Notification'), 'notification/register') . '</p>';

  return theme('table', $headers, $rows, array(), $caption);
}

function notification_eventlog_page($serial) {

  $sql = "
    SELECT
      FROM_UNIXTIME(l.time + u.timezone, '%s') AS time,
      e.name AS name
    FROM
      {users} u,
      {logger_devices} d,
      {event} e,
      {event_log} l
    WHERE
      l.event_id = e.id AND
      l.device = d.device AND
      d.serial = '%s' AND
      d.uid = u.uid";

  $args = array(TIMESTAMP_FORMAT, $serial);

  $headers = array(
    array('data' => t('Time'),  'field' => 'time', 'sort' => 'DESC'),
    array('data' => t('Event'), 'field' => 'name', 'sort' => 'ASC'),
  );

  $sql_count = "
    SELECT
      COUNT(*)
    FROM
      {logger_devices} d,
      {event_log} l
    WHERE
      l.device = d.device AND
      d.serial = '$serial'";

  $sql .= tablesort_sql($headers);

  $limit = 20;
  $result = pager_query($sql, $limit, 0, $sql_count, $args);
  $rows = array();

  while ($entry = db_fetch_array($result)) {
    $rows[] = array(
      'time' => $entry['time'],
      'name' => t($entry['name'])
    );
  }

  $caption = '<p>' . t('Serial Number') . ': ' . $serial . '</p>' . '<p>' .
    l(t('Clear'), 'event/log/clear/' . $serial) . '</p>';

  $output = theme('table', $headers, $rows, array(), $caption);
  $output .= theme('pager', NULL, $limit, 0);

  return $output;
}

function _notification_eventlog_clear($serial) {

  $sql = "DELETE FROM {event_log} WHERE device = (SELECT d.device FROM {logger_devices} d WHERE d.serial = '%s')";
  db_query($sql, $serial);

  return notification_eventlog_page($serial);
}

/**
 * Removes log entries older than 1 week.
 *
 * @param $now The event checkup time.
 */
function _notification_eventlog_clear_old($now) {

  $sql = "DELETE FROM {event_log} WHERE time < %d";
  db_query($sql, $now - WEEK);
}

/**
 * Logs the "brownout" event.
 *
 * @param $device  The device where the event occurred.
 */
function notification_log_brownout($device) {

  _notification_log_event(BROWNOUT_EVENT_ID, $device);
}

/**
 * Logs the "heartbeat received" event.
 *
 * @param $device  The device where the event occurred.
 */
function notification_log_heartbeat_received($device) {

  _notification_log_event(HEARTBEAT_RECEIVED_EVENT_ID, $device);
}

/**
 * Logs the "measurement received" event.
 *
 * @param $device  The device where the event occurred.
 */
function notification_log_measurement_received($device) {

  _notification_log_event(MEASUREMENT_RECEIVED_EVENT_ID, $device);
}

/**
 * Logs the "corrupted measurement" event.
 *
 * @param $device  The device where the event occurred.
 */
function notification_log_corrupted_measurement($device) {

  _notification_log_event(CORRUPTED_MEASUREMENT_EVENT_ID, $device);
}

/**
 * Logs an event.
 *
 * @param $event_id  The event id.
 * @param $device    The device where the event occurred.
 */
function _notification_log_event($event_id, $device) {

  $sql = "INSERT INTO {event_log} (device, event_id, time) VALUES ('%s', %d, %d)";
  db_query($sql, $device, $event_id, time());
}

/**
 * Builds the newsletter registration page.
 *
 * @return the newsletter registration page.
 */
function notification_newsletter_page() {

  $output = '<div><p>' .
    t('We would also like to keep up to date via email. Please use the form below to sign up for our newsletter.') .
    '<br><br></p></div>';

  $output .= drupal_get_form('notification_newsletter_form');

  $output .= '<div><p><br><br><br>' .
    t('Of course, we do not share this information with anyone at any given time. If you want to unsubscribe, please click the appropriate link found at the end of each newsletter.') .
    '</p></div>';

  return $output;
}

function notification_registration_form() {

  global $user;

  $form['device'] = array(
    '#type'           => 'select',
    '#title'          => t('Serial Number'),
    '#description'    => t('Select the serial number of the monitored device.'),
    '#options'        => logger_get_devices_options()
  );

  $form['emails'] = array(
    '#type'              => 'textarea',
    '#title'             => t('E-mails'),
    '#description'       => t('Enter the e-mails to which the notification will be sent. The emails must be specified either in multiple lines or separated by space.'),
    '#rows'              => 3,
    '#resizable'         => FALSE,
    '#default_value'     => $user->mail,
    '#element_validate'  => array('notification_emails_validate')
  );

  $form['events'] = array(
    '#type'           => 'fieldset',
    '#title'          => t('Events'),
    '#prefix'         => '<br><table width="100%">',
    '#suffix'         => '</table>'
  );

  $form['events']['event_id1'] = array(
    '#title'          => _notification_get_event_name(NO_COMMUNICATION_EVENT_ID),
    '#type'           => 'checkbox',
    '#default_value'  => FALSE,
    '#prefix'         => '<tr><td>',
    '#suffix'         => '</td>',
    '#attributes'     => array(
      'onchange' => '
        limit_up1 = document.getElementById("limit_up1");
        limit_up1.readOnly = !this.checked;
        limit_up1.value = this.checked ? 2 : "";
        unit_id1 = document.getElementById("unit_id1");
        unit_id1.value = ' . HOUR_UNIT_ID . ';',
    ),
  );

  $form['events']['limit_up1'] = array(
    '#type'              => 'textfield',
    '#description'       => t('Here you can set the maximum heartbeat delay. Beyond this limit, the device is considered faulty.'),
    '#maxlength'         => 9,
    '#size'              => 12,
    '#prefix'            => '<td>',
    '#suffix'            => '</td>',
    '#related_event_id'  => NO_COMMUNICATION_EVENT_ID,
    '#element_validate'  => array('notification_limit_up_validate'),
    '#attributes'        => array(
      'onfocus' => '
        event_id1 = document.getElementById("event_id1");
        this.readOnly = !event_id1.checked;',
    ),
  );

  $form['events']['unit_id1'] = array(
    '#type'           => 'select',
    '#prefix'         => '<td width="200">',
    '#suffix'         => '</td></tr>',
    '#default_value'  => HOUR_UNIT_ID,
    '#required'       => TRUE,
    '#options'        => _notification_get_units_options(NO_COMMUNICATION_EVENT_ID),
  );

  $form['events']['event_id4'] = array(
    '#title'          => _notification_get_event_name(PEAK_CONSUMPTION_EVENT_ID),
    '#type'           => 'checkbox',
    '#default_value'  => FALSE,
    '#prefix'         => '<tr><td>',
    '#suffix'         => '</td>',
    '#attributes'     => array(
      'onchange' => '
        limit_up4 = document.getElementById("limit_up4");
        limit_up4.readOnly = !this.checked;
        limit_up4.value = this.checked ? 5000 : "";
        unit_id4 = document.getElementById("unit_id4");
        unit_id4.value = ' . WATT_HOUR_UNIT_ID . ';',
    ),
  );

  $form['events']['limit_up4'] = array(
    '#type'             => 'textfield',
    '#description'      => t('Here you can set the maximum electricity consumption. Beyond this limit, the device is considered faulty.'),
    '#maxlength'        => 12,
    '#size'             => 12,
    '#prefix'           => '<td>',
    '#suffix'           => '</td>',
    '#related_event_id' => PEAK_CONSUMPTION_EVENT_ID,
    '#element_validate' => array('notification_limit_up_validate'),
    '#attributes'       => array(
      'onfocus' => '
        event_id4 = document.getElementById("event_id4");
        this.readOnly = !event_id4.checked;',
    ),
  );

  $form['events']['unit_id4'] = array(
    '#type'           => 'select',
    '#prefix'         => '<td width="200">',
    '#suffix'         => '</td></tr>',
    '#default_value'  => WATT_HOUR_UNIT_ID,
    '#required'       => TRUE,
    '#options'        => _notification_get_units_options(PEAK_CONSUMPTION_EVENT_ID),
  );

  $form['events']['event_id2'] = array(
    '#title'          => _notification_get_event_name(CORRUPTED_MEASUREMENT_EVENT_ID),
    '#type'           => 'checkbox',
    '#default_value'  => FALSE,
    '#prefix'         => '<tr><td colspan="3"/>',
    '#suffix'         => '</tr>'
  );

  $form['min_interval'] = array(
    '#type'           => 'select',
    '#title'          => t('Amount of Notifications'),
    '#description'    => t('How often do you want to receive notifications, when the same event occurs several times consecutively?'),
    '#default_value'  => 0,
    '#required'       => TRUE,
    '#options'        => _notification_get_frequency_options(),
  );

  $form['submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Save'),
  );

  return $form;
}

function notification_edition_form(&$form_state, $notification) {

  $form['device'] = array(
    '#type'              => 'hidden',
    '#required'          => TRUE,
    '#default_value'     => $notification->device,
  );

  $form['event_id'] = array(
    '#type'              => 'hidden',
    '#default_value'     => $notification->event_id,
  );

  $form['old_limit_up'] = array(
    '#type'              => 'hidden',
    '#default_value'     => $notification->limit_up,
  );

  $form['old_unit_id'] = array(
    '#type'              => 'hidden',
    '#default_value'     => $notification->unit_id,
  );

  $form['event_name'] = array(
    '#type'              => 'textfield',
    '#title'             => t('Event'),
    '#required'          => TRUE,
    '#default_value'     => t($notification->event_name),
    '#attributes'        => array('readOnly' => 'true')
  );

  $form['serial'] = array(
    '#type'              => 'textfield',
    '#title'             => t('Serial Number'),
    '#required'          => TRUE,
    '#default_value'     => $notification->serial,
    '#attributes'        => array('readOnly' => 'true')
  );

  $form['emails'] = array(
    '#type'              => 'textarea',
    '#title'             => t('E-mails'),
    '#description'       => t('Enter the e-mails to which the notification will be sent. The emails must be specified either in multiple lines or separated by space.'),
    '#rows'              => 3,
    '#resizable'         => FALSE,
    '#required'          => TRUE,
    '#default_value'     => $notification->emails,
    '#element_validate'  => array('notification_emails_validate')
  );

  switch ($notification->event_id) {
    case NO_COMMUNICATION_EVENT_ID:
      $form['limit_up'] = array(
        '#type'              => 'textfield',
        '#title'             => t('Maximum Delay'),
        '#description'       => t('Here you can set the maximum heartbeat delay. Beyond this limit, the device is considered faulty.'),
        '#required'          => TRUE,
        '#maxlength'         => 9,
        '#size'              => 12,
        '#prefix'            => '<table border="0"><tr><td>',
        '#suffix'            => '</td>',
        '#default_value'     => $notification->limit_up,
        '#element_validate'  => array('notification_limit_up_validate'),
      );
      break;

    case PEAK_CONSUMPTION_EVENT_ID:
      $form['limit_up'] = array(
        '#type'              => 'textfield',
        '#title'             => t('Maximum Consumption'),
        '#description'       => t('Here you can set the maximum electricity consumption. Beyond this limit, the device is considered faulty.'),
        '#required'          => TRUE,
        '#maxlength'         => 9,
        '#size'              => 12,
        '#prefix'            => '<table><tr><td>',
        '#suffix'            => '</td>',
        '#default_value'     => $notification->limit_up,
        '#element_validate'  => array('notification_limit_up_validate'),
      );
      break;
  }

  if ($notification->event_id <> CORRUPTED_MEASUREMENT_EVENT_ID) {

    $form['unit_id'] = array(
      '#type'           => 'select',
      '#required'       => TRUE,
      '#prefix'         => '<td width="150">',
      '#suffix'         => '</td></tr></table>',
      '#default_value'  => $notification->unit_id,
      '#options'        => _notification_get_units_options($notification->event_id),
    );
  }

  $form['min_interval'] = array(
    '#type'           => 'select',
    '#title'          => t('Amount of Notifications'),
    '#description'    => t('How often do you want to receive notifications, when the same event occurs several times consecutively?'),
    '#required'       => TRUE,
    '#options'        => _notification_get_frequency_options(),
    '#default_value'  => $notification->min_interval,
  );

  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function notification_newsletter_form() {

  $form['email'] = array(
    '#type'             => 'textfield',
    '#title'            => t('E-mail'),
    '#description'      => t('Enter your e-mail.'),
    '#maxlength'        => 64,
    '#size'             => 20,
    '#required'         => 1,
    '#element_validate' => array('notification_email_validate'),
  );

  $form['firstname'] = array(
    '#type'             => 'textfield',
    '#title'            => t('First Name'),
    '#description'      => t('Enter your first name.'),
    '#maxlength'        => 20,
    '#required'         => 1,
    '#size'             => 20,
  );

  $form['lastname'] = array(
    '#type'             => 'textfield',
    '#title'            => t('Last Name'),
    '#description'      => t('Enter your last name.'),
    '#maxlength'        => 20,
    '#required'         => 1,
    '#size'             => 20,
  );

  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t("Subscribe"),
  );

  return $form;
}

function notification_email_validate($field, $form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
    form_error($field, t('Invalid e-mail address.'));
  }
}

function notification_emails_validate($field, $form_state) {

  $emails = _notification_tokenize_emails($form_state['values']['emails']);

  if (count($emails) > 10) {
    form_error($field, t('Inform at most 10 e-mails.'));
  }

  foreach($emails as $email) {

    if (!valid_email_address($email)) {

      form_error($field, t('Invalid e-mail address.'));
      return;
    }
  }
}

function notification_limit_up_validate($field, $form_state) {

  //Checkbox field
  $related_event_id = $field['#related_event_id'];
  $selected = $form_state['values']["event_id$related_event_id"];

  //If selected
  if ($selected) {

    $limit_up = $form_state['values']["limit_up$related_event_id"];
    $unit_id = $form_state['values']["unit_id$related_event_id"];

    $factor = db_result(db_query("SELECT factor FROM {unit} un WHERE id = %d", $unit_id));
    $converted_limit = $limit_up * $factor;

    if ($related_event_id == NO_COMMUNICATION_EVENT_ID && $converted_limit < 30 * MINUTE) {

      form_error($field, t('Delay time can not be less than 30 minutes.'));

    } else if ($related_event_id == PEAK_CONSUMPTION_EVENT_ID && $converted_limit <= 0) {

      form_error($field, t('Peak consumption can not be lesser than 0 watt / min.'));
    }
  }
}

function notification_registration_form_submit($form, &$form_state) {

  _notification_register_event($form, $form_state, NO_COMMUNICATION_EVENT_ID);
  _notification_register_event($form, $form_state, CORRUPTED_MEASUREMENT_EVENT_ID);
  _notification_register_event($form, $form_state, PEAK_CONSUMPTION_EVENT_ID);

  $form_state['redirect'] = 'notification/list';
}

function notification_edition_form_submit($form, &$form_state) {

  _notification_edit_event($form, $form_state);

  $form_state['redirect'] = 'notification/list';
}

function notification_newsletter_form_submit($form, &$form_state) {

  $email     = $form_state['values']['email'];
  $firstname = $form_state['values']['firstname'];
  $surname   = $form_state['values']['surname'];

  $url = 'http://www.eor.de/fileadmin/verwaltung/mysmartgrid.php' .
    '?email='     . urlencode($email) .
    '&firstname=' . urlencode($firstname) .
    '&surname='   . urlencode($surname);
  //For testing, include '&test=1'

  $request = drupal_http_request($url);
  $response = $request->data;

  if ($response == "RECORD_CREATED") {

    drupal_set_message(t('Almost Finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you.'));

  } else if ($response == "RECORD_UPDATED") {

    drupal_set_message(t('The e-mail address was already present in the database. The user data has been updated.'));

  } else {

    drupal_set_message(t('Our apologies. The newsletter subscription is temporarily unavailable. Please, try again later.'));

    _notification_send_system_error_email('newsletter', $response, $url);
  }

  return $output;
}

function _notification_register_event($form, $form_state, $event_id) {

  $selected = $form_state['values']["event_id$event_id"];

  if ($selected) {

    $device       = $form_state['values']['device'];
    $limit_up = $form_state['values']["limit_up$event_id"];
    $unit_id  = $form_state['values']["unit_id$event_id"];

    $emails       = $form_state['values']['emails'];
    $min_interval = $form_state['values']['min_interval'];

    _notification_delete($device, $event_id, $limit_up, $unit_id);
    _notification_insert($device, $event_id, $emails, $min_interval, $limit_up, $unit_id);
  }
}

function _notification_edit_event($form, $form_state) {

  $device   = $form_state['values']['device'];
  $event_id = $form_state['values']["event_id"];
  $old_limit_up = $form_state['values']["old_limit_up"];
  $old_unit_id  = $form_state['values']["old_unit_id"];

  $limit_up = $form_state['values']["limit_up"];
  $unit_id  = $form_state['values']["unit_id"];
  $emails       = $form_state['values']['emails'];
  $min_interval = $form_state['values']['min_interval'];

  _notification_delete($device, $event_id, $old_limit_up, $old_unit_id);
  _notification_delete($device, $event_id, $limit_up, $unit_id);
  _notification_insert($device, $event_id, $emails, $min_interval, $limit_up, $unit_id);
}

/**
 * Converts a string containing a list of emails into an array.
 *
 * @param $str  The string containing emails separated by space, new line char, or tab char.
 * @return an array of emails.
 */
function _notification_tokenize_emails($str) {

  $sep = " \n\r";
  $tokens = array();

  $token = strtok($str, $sep);

  while ($token !== FALSE) {

    $tokens[] = trim($token, $sep);
    $token = strtok($sep);
  }

  return $tokens;
}

/**
 * Returns an event name.
 *
 * @param $event_id  The event id.
 * @return the event name.
 */
function _notification_get_event_name($event_id) {

  $sql = "SELECT name FROM {event} WHERE id = %d";
  $name = db_result(db_query($sql, $event_id));

  return t($name);
}

/**
 * Returns an array of units associated with the informed event, indexed by their respective ids.
 * @param $event_id The event id.
 *
 * @return the array of units.
 */
function _notification_get_units_options($event_id) {

  $sql = "
    SELECT
      un.id,
      un.name
    FROM
      {unit} un,
      {event_unit} eu
    WHERE
      eu.event_id = %d AND
      eu.unit_id = un.id
    ORDER BY
      un.id";

  $result = db_query($sql, $event_id);

  $units = array();
  while ($row = db_fetch_array($result)) {
    $units[$row['id']] = t($row['name']);
  }

  return $units;
}

/**
 * Returns an array of notification frequencies indexed by their respective
 * time intervals in minutes.
 *
 * @return the array of frequencies.
 */
function _notification_get_frequency_options() {
  return array(
      0          => t('No limit, notify every single event'),
     30 * MINUTE => t('2 notifications per hour'),
      1 * HOUR   => t('1 notification per hour'),
     12 * HOUR   => t('2 notifications per day'),
      1 * DAY    => t('1 notification per day')
  );
}

/**
 * Deletes an event notification.
 *
 * @param $device    The monitored device.
 * @param $event_id  The event id.
 * @param $limit_up  The event's threshold.
 * @param $unit_id   The unit id.
 */
function _notification_delete($device, $event_id, $limit_up, $unit_id) {

  $sql = "
    DELETE FROM
      {notification}
    WHERE
      device = '%s' AND
      event_id = %d AND
      limit_up = %f AND
      unit_id = %d";

  db_query($sql, $device, $event_id, $limit_up, $unit_id);
}

/**
 * Registers an event notification.
 *
 * @param $device        The monitored device.
 * @param $event_id      The event id.
 * @param $emails        The notification e-mail.
 * @param $min_interval  The minimum time interval between consecutive notifications of the same event.
 * @param $limit_up      An event-related maximum value.
 * @param $unit_id       The unit id.
 */
function _notification_insert($device, $event_id, $emails, $min_interval, $limit_up, $unit_id) {

  $base_value = 0;

  if ($event_id == PEAK_CONSUMPTION_EVENT_ID) {

    $sql = "
      SELECT
        SUM(m.value) AS total
      FROM
        {logger_meters} m
      WHERE
        m.type   = '%s' AND
        m.device = '%s' ";

    //Note: the values are stored in unit 'watt'
    $base_value = db_result( db_query($sql, 'electricity', $device));
  }

  $sql = "
    INSERT INTO
      {notification} (device, event_id, emails, min_interval, base_value, base_time, limit_up, unit_id, last_sent)
    VALUES
      ('%s', %d, '%s', %d, %d, %d, %f, %d, %d)";

  db_query($sql, $device, $event_id, $emails, $min_interval, $base_value, time(), $limit_up, $unit_id, 0);
}

/**
 * Updates an event notification.
 *
 * @param $device    The monitored device.
 * @param $event_id  The event id.
 * @param $last_sent The timestamp when the latest email was sent.
 */
function _notification_update($device, $event_id, $last_sent) {

  $sql = "
    UPDATE
      {notification}
    SET
      last_sent = %d
    WHERE
      device = '%s' AND
      event_id = %d";

  db_query($sql, $last_sent, $device, $event_id);
}

function notification_cron() {

  $now = time();

  _notification_send_no_communication_emails($now);
  _notification_send_corrupted_measurement_emails($now);
  _notification_send_peak_consumption_emails($now);

  _notification_eventlog_clear_old($now);
}

/**
 * Sends e-mails notifying users of "No Communication" events.
 *
 * @param $now The event checkup time.
 */
function _notification_send_no_communication_emails($now) {

  $sql = "
    SELECT
      %d AS event_id,
      n.device AS device,
      n.serial AS serial,
      n.emails AS emails,
      FROM_UNIXTIME(n.access + n.timezone, '%s') AS event_time,
      ROUND((n.limit_up / 60), 2) AS limit_up
    FROM
      (
        SELECT
          d.device AS device,
          d.serial AS serial,
          n.emails AS emails,
          (n.limit_up * un.factor) AS limit_up,
          n.last_sent AS last_sent,
          n.min_interval AS min_interval,
          IF(d.access > MAX(m.access), d.access, MAX(m.access)) AS access,
          u.timezone AS timezone
        FROM
          {logger_meters} m,
          {logger_devices} d,
          {notification} n,
          {unit} un,
          {users} u
        WHERE
          m.device = d.device AND
          d.device = n.device AND
          n.event_id = %d AND
          n.unit_id = un.id AND
          d.uid = u.uid
        GROUP BY
          d.device,
          n.limit_up,
          n.unit_id
        HAVING
          SUM(m.corrupted) = 0
      ) n
    WHERE
      %d > (n.access + n.limit_up) AND
      %d > (n.last_sent + n.limit_up) AND
      %d > (n.last_sent + n.min_interval)";

  $event_id = NO_COMMUNICATION_EVENT_ID;
  $args = array($event_id, TIMESTAMP_FORMAT, $event_id, $now, $now, $now);

  //ATTENTION: Any change in the following message requires its translations to be redefined.
  $message = _notification_compose_error_email(
    "Your Flukso device (serial number: %serial) has not been sending " .
    "data for more than %limit_up minutes, since %event_time.",

    "Check your WLAN configuration and make sure that it remains active for " .
    "at least 1 hour per day. The device might be working fine, but it is " .
    "failing to send the heartbeats over the internet.");

  _notification_send_emails($message, $sql, $args);
}

/**
 * Sends e-mails notifying users of "Corrupted Measurement" events.
 *
 * @param $now The event checkup time.
 */
function _notification_send_corrupted_measurement_emails($now) {

  $sql = "
    SELECT
      %d AS event_id,
      d.device AS device,
      d.serial AS serial,
      n.emails AS emails,
      FROM_UNIXTIME(m.corrupted + u.timezone, '%s') AS event_time
    FROM
      {users} u,
      {logger_devices} d,
      {logger_meters} m,
      {notification} n
    WHERE
      d.uid = u.uid AND
      d.device = n.device AND
      n.event_id = %d AND
      %d > (n.last_sent + n.min_interval) AND
      m.device = d.device AND
      m.corrupted <> 0";

  $event_id = CORRUPTED_MEASUREMENT_EVENT_ID;
  $args = array($event_id, TIMESTAMP_FORMAT, $event_id, $now);

  //ATTENTION: Any change in the following message requires its translations to be redefined.
  $message = _notification_compose_error_email(
    "Your Flukso device (serial number: %serial) has sent a measurement with " .
    "corrupted data at %event_time.");

  _notification_send_emails($message, $sql, $args);
}

/**
 * Sends em-mails notifying users of the occurrence of Peak Consumption events.
 *
 * @param $now The event checkup time.
 */
function _notification_send_peak_consumption_emails($now) {

  $sql = "
    SELECT
      %d AS event_id,
      n.device AS device,
      n.serial AS serial,
      n.emails AS emails,
      FROM_UNIXTIME(latest_access + n.timezone, '%s') AS event_time,
      ROUND(n.limit_up, 2) AS limit_up,
      (n.base_time + n.timezone) AS start_time,
      n.consumption AS consumption,
      n.elapsed_time AS elapsed_time,
      n.timezone AS timezone
    FROM
      (
        SELECT DISTINCT
          d.device AS device,
          d.serial AS serial,
          n.emails AS emails,
          (n.limit_up * un.factor * 60) AS limit_up,
          (SUM(m.value) - n.base_value) AS consumption,
          MAX(m.access) AS latest_access,
          n.base_time AS base_time,
          ((MAX(m.access) - n.base_time) / 3600) AS elapsed_time,
          u.timezone AS timezone
        FROM
          {users} u,
          {logger_devices} d,
          {logger_meters} m,
          {notification} n,
          {unit} un
        WHERE
          d.uid = u.uid AND
          d.device = n.device AND
          n.event_id = %d AND
          n.unit_id = un.id AND
          %d > (n.last_sent + n.min_interval) AND
          m.device = d.device AND
          m.type = '%s'
        GROUP BY
          d.device
        HAVING
          latest_access > base_time AND
          consumption > 0
      ) n
    WHERE
      (n.consumption / n.elapsed_time) > n.limit_up";

  $event_id = PEAK_CONSUMPTION_EVENT_ID;
  $args = array($event_id, TIMESTAMP_FORMAT, $event_id, $now, 'electricity');

  //ATTENTION: Any change in the following message requires its translations to be redefined.
  $message = _notification_compose_email(
    "At %event_time, your Flukso device (serial number: %serial) has registered " .
    "an electricity consumption above the limit of %limit_up watt per hour.<br><br> " .

    "The device's latest measurements are listed in the following.<br><br> " .
    "!latest_measurements <br><br>");

  _notification_send_emails($message, $sql, $args);

  _notification_register_power_consumption();
}

/**
 * Registers the power consumption of monitored devices every hour and after
 * notifications are sent.
 */
function _notification_register_power_consumption() {

  //Note: the values are stored in unit 'watt'

  $sql = "
    UPDATE
      {notification}
    SET
      base_time = (
        SELECT
          MAX(m.access)
        FROM
          {logger_meters} m
        WHERE
          m.type = '%s' AND
          m.device = notification.device),
      base_value = (
        SELECT
          SUM(m.value)
        FROM
          {logger_meters} m
        WHERE
          m.type = '%s' AND
          m.device = notification.device)
    WHERE
      event_id = %d";

  db_query($sql, 'electricity', 'electricity', PEAK_CONSUMPTION_EVENT_ID);
}

/**
 * Notifies the administrator of the occurrence of a system error.
 *
 * @param $context     The page or function where the error occurred.
 * @param $error_code  The error code.
 * @param $url         The URL that triggered the error (if any).
 */
function _notification_send_system_error_email($context, $error_code, $url) {

  //ATTENTION: Any change in the following message requires its translations to be redefined.

  $error_descriptions['newsletter']['ERROR_INVALID_DATA'] =
    'Invalid e-mail address.';

  $error_descriptions['newsletter']['ERROR_INSERT_FAILED'] =
    'Error while inserting the record in mySQL database.';

  $error_descriptions['newsletter']['ERROR_UPDATE_FAILED'] =
    'Error while updating the record in mySQL database.';

  $message =
    "<p>Dear Administrator " .
    "<br> &nbsp;<br></p> " .

    "<p>The following system error has been reported.</p> " .
    "<p>Error code: %error_code<br> " .
    "Description: %description<br> " .
    "Related URL: %url</p> " .

    "<p>&nbsp;<br> " .
    "<p>mySmartGrid System</p>";

  $variables['%error_code'] = $error_code;
  $variables['%description'] = t($error_descriptions[$context][$error_code]);
  $variables['%url'] = $url;

  $body = t($message, $variables);
  $subject = t('System Error');
  $email = 'notifications@mysmartgrid.de';

  _notification_send_email($email, $subject, $body);
}

/**
 * Composes an e-mail that notifies a general event.
 *
 * @param $description  The event description.
 * @param $complement   Complementary information about the error.
 * @return the e-mail message.
 */
function _notification_compose_email($description, $complement = NULL) {

  //ATTENTION: Any change in the following message requires its translations to be redefined.

  $complement = $complement == NULL? "" : "<p>$complement</p> ";

  return
    "<p>Dear user " .
    "<br> &nbsp;<br></p> " .

    "<p>$description</p> " .

    $complement .

    "<p>If you want to stop receiving this notification, please remove it from your " .
    "<a href='!base_url/notification/list'>event notifications list</a>.</p> " .

    "<p>&nbsp;<br> " .
    "Best Regards,</p> " .
    "<p>mySmartGrid Team</p>";
}

/**
 * Composes an e-mail that notifies an error event.
 *
 * @param $description    The error description.
 * @param $recommendation The recommendation for the user of how to solve the problem.
 * @return the e-mail message.
 */
function _notification_compose_error_email($description, $recommendation = NULL) {

  $recommendation = $recommendation == NULL? "": "<li>$recommendation<br><br>";

  //ATTENTION: Any change in the following message requires its translations to be redefined.
  return _notification_compose_email($description,

    "In order to identify and solve the problem, please take the following actions. " .
    "<ul> " .
      $recommendation .

      "<li>Check if the device complies with the " .
      "<a href='!base_url/content/installationsanleitung-des-fluksos'>Flukso installation instructions</a>. " .
      "It might be improperly installed or misconfigured.<br><br> " .

      "<li>Visit our <a href='!base_url/content/h&#228;ufige-fragen-und-antworten'>FAQ</a>, " .
      "and read the answers to questions made by other users in similar situations.<br><br> " .

      "<li>In case the problem persists, please send an e-mail to msg-support@itwm.fhg.de. " .
    "</ul>");
}

/**
 * Sends event notification e-mails to notifiable users.
 *
 * @param $message    The e-mail message.
 * @param $sql        The SQL statement for selecting the events.
 *                    Each field is mapped to a message variable.
 * @param $args       The SQL arguments.
 */
function _notification_send_emails($message, $sql, $args = array()) {

  global $base_url;
  $variables = array();
  $variables["!base_url"] = $base_url;

  $result = db_query($sql, $args);

  while ($object = db_fetch_array($result)) {

    foreach ($object as $key => $value) {
      $variables["%$key"] = $value;
    }

    if (strpos($message, 'latest_measurements')) {

      $variables['!latest_measurements'] = _notification_query_latest_measurements(
          $object['device'],
          $object['start_time'],
          $object['timezone']);
    }

    $subject = t('Event Notification');

    $logo = "<p><img src='$base_url/sites/all/themes/mysmartgrid/logo.png'/></p>";
    $body = t($message, $variables) . $logo;

    $emails = $object['emails'];
    foreach (_notification_tokenize_emails($emails) as $email) {

      _notification_send_email($email, $subject, $body);
    }

    _notification_update($object['device'], $object['event_id'], time());
  }
}

/**
 * Returns a list of measurements performed by all sensors of the informed device.
 *
 * @param $device     The device's hash code.
 * @param $start_time The start time of the period being searched.
 * @param $offset     The user timezone offset.
 * @return an HTML list of measurements.
 */
function _notification_query_latest_measurements($device, $start_time, $offset) {

  $measurements = logger_query_device_measurements('hour', $device, $offset);
  $list = '';
  $sum = 0;

  foreach ($measurements as $meter => $data) {
    foreach ($data as $function => $values) {
      $sublist = NULL;

      foreach ($values as $timestamp => $value) {

        if ($value > 0 && $timestamp >= $start_time) {

          $sum += $value;

          $sublist = $sublist? $sublist : t('Sensor') . ': ' . $function . '<br> ';
          $sublist .= date('Y-m-d H:i', $timestamp) . ' - ' .
            number_format($value, 2, '.', '') . ' ' . t('watt') . '<br> ';
        }
      }
      $list .= $sublist;
    }
  }

  if ($sum > 0) {
    $tabs = str_repeat('&nbsp', 25);
    $list .= '--------------------------------------------- <br>' .
      "Sum$tabs " . number_format($sum, 2, '.', '') . ' ' . t('watt') . ' <br>';
  }

  return $list;
}

/**
 * Sends a notification e-mail.
 *
 * @param $email    The e-mail address.
 * @param $subject  The e-mail subject.
 * @param $body     The e-mail body.
 */
function _notification_send_email($email, $subject, $body) {

  global $language;

  $params = array(
    'subject' => $subject,
    'body' => $body
  );

  drupal_mail('notification', 'notice', $email, $language, $params);
}

function notification_mail($key, &$message, $params) {

  $message['headers']['Content-Type'] = "text/html; charset=UTF-8";
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}