<?php

/**
 * Support module for charting flukso measurements.
 *
 * Copyright (c) 2008-2009 jokamajo.org
 *               2010 flukso.net
 *               2010 Fraunhofer Institut ITWM (www.itwm.fraunhofer.de)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

//Constants
define('MINUTE', 60);
define('HOUR',   60 * MINUTE);
define('DAY',    24 * HOUR);
define('WEEK',    7 * DAY);
define('YEAR',   52 * WEEK);

define('ROOT_PATH',  drupal_get_path('module', 'logger'));
define('CHART_HEIGHT', 350);
define('SLIDER_HEIGHT', 50);

define('CHART_UNIT_ID', 'logger_chart_unit_');
define('SERIES_COLOR_ID', 'logger_series_color_');
define('SMOOTHING_LEVEL_ID', 'logger_smooting_level_');
define('STEP_PLOT_ID', 'logger_step_plot_');

function logger_init() {

  drupal_add_js(ROOT_PATH . '/js/jscolor/jscolor.js');
  drupal_add_js(ROOT_PATH . '/js/charts.js');

  //If IE
  if (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE')) {
    drupal_add_js(ROOT_PATH . '/js/dygraph/excanvas.js');
  }

  drupal_add_js(ROOT_PATH . '/js/dygraph/strftime-min.js');
  drupal_add_js(ROOT_PATH . '/js/dygraph/rgbcolor.js');
  drupal_add_js(ROOT_PATH . '/js/dygraph/dygraph-canvas.js');
  drupal_add_js(ROOT_PATH . '/js/dygraph/dygraph.js');

  jquery_ui_add(array('ui.datepicker'));
  drupal_add_css(ROOT_PATH . '/style/ui.datepicker.css');

  drupal_add_js(ROOT_PATH . '/js/flot/jquery.flot.js');
  drupal_add_js(ROOT_PATH . '/js/flot/jquery.flot.stack.js');
}

function logger_perm() {
  return array('logger', 'register devices');
}

function logger_menu() {

  $items = array();

  // Main operations

  $items['logger'] = array(
    'title'            => 'Homepage',
    'description'      => 'Show the home page',
    'page callback'    => '_logger_home_page',
    'page arguments'   => array(1, 2),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['overview'] = array(
    'title'            => 'Overview',
    'description'      => 'Show the project overview',
    'page callback'    => '_logger_overview_page',
    'page arguments'   => array(1, 2),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['energy'] = array(
    'title'            => 'Your energy consumption',
    'description'      => 'Show the energy consumption page',
    'page callback'    => '_logger_energy_page',
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['energy/relative'] = array(
    'title'            => 'Relative',
    'description'      => 'Show the relative energy consumption page',
    'page callback'    => '_logger_relative_energy_consumption_page',
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['power'] = array(
    'title'            => 'Your power consumption',
    'description'      => 'Show the power consumption page',
    'page callback'    => '_logger_power_page',
    'page arguments'   => array(1, 2),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['logger/color'] = array(
    'title'            => 'Changes the series color',
    'page callback'    => '_logger_series_color',
    'page arguments'   => array(2, 3, 4),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['logger/smoothinglevel'] = array(
    'title'            => 'Changes the chart smoothing level',
    'page callback'    => '_logger_set_smoothing_level',
    'page arguments'   => array(2),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['logger/remove/user'] = array(
    'title'            => 'Removes a chart series',
    'page callback'    => '_logger_remove_user',
    'page arguments'   => array(3),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );

  $items['logger/file'] = array(
    'title'            => 'Downloads a chart file',
    'page callback'    => '_logger_download_chart_data_file',
    'page arguments'   => array(2),
    'access callback'  => TRUE,
    'type'             => MENU_CALLBACK
  );


  //Devices' operations

  $items['user/%user_uid_optional/devices'] = array(
    'title'            => 'Devices',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('_logger_account_devices'),
    'access callback'  => '_logger_account_access',
    'access arguments' => array('register devices', 1),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'logger.admin.inc',
    'weight'           => 3,
  );

  $items['device/deactivate'] = array(
    'title'            => $items['user/%user_uid_optional/devices']['title'],
    'page callback'    => '_logger_device_deactivate',
    'page arguments'   => array(2),
    'access callback'  => '_logger_device_access',
    'access arguments' => array('logger', 2),
    'type'             => MENU_CALLBACK,
    'file'             => 'logger.admin.inc'
  );


  //Sensors' operations

  $items['user/%user_uid_optional/sensors'] = array(
    'title'            => 'Sensors',
    'page callback'    => '_logger_account_sensors',
    'access callback'  => '_logger_account_access',
    'access arguments' => array('logger', 1),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'logger.admin.inc',
    'weight'           => 3,
  );

  $items['sensor/edit'] = array(
    'title'            => 'Sensor Edition',
    'page callback'    => '_logger_sensor_edit',
    'page arguments'   => array(2),
    'access callback'  => '_logger_sensor_access',
    'access arguments' => array('logger', 2),
    'type'             => MENU_CALLBACK,
    'file'             => 'logger.admin.inc'
  );

  $items['sensor/deactivate'] = array(
    'title'            => $items['user/%user_uid_optional/sensors']['title'],
    'page callback'    => '_logger_sensor_deactivate',
    'page arguments'   => array(2),
    'access callback'  => '_logger_sensor_access',
    'access arguments' => array('logger', 2),
    'type'             => MENU_CALLBACK,
    'file'             => 'logger.admin.inc'
  );

  $items['sensor/activate'] = array(
    'title'            => $items['sensor/edit']['title'],
    'page callback'    => '_logger_sensor_activate',
    'page arguments'   => array(2),
    'access callback'  => '_logger_sensor_access',
    'access arguments' => array('logger', 2),
    'type'             => MENU_CALLBACK,
    'file'             => 'logger.admin.inc'
  );


  /* Other operations */

  $items['admin/settings/logger'] = array(
    'title'            => 'Logger settings',
    'description'      => 'Configure settings for logging metering values.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('_logger_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  $items['user/%user_uid_optional/privacy'] = array(
    'title'            => 'Privacy',
    'page callback'    => '_logger_account_privacy',
    'access callback'  => '_logger_account_access',
    'access arguments' => array('logger', 1),
    'type'             => MENU_LOCAL_TASK,
    'file'             => 'logger.admin.inc',
    'weight'           => 2,
  );

  return $items;
}

/**
 * Forwards request to a suitable home page.
 *
 * @param $type     The sensor type.
 * @param $interval The time interval.
 * @return the home page.
 */
function _logger_home_page($type, $interval) {

  if (user_access('logger')) {
    return _logger_energy_page();

  } else {
    return _logger_overview_page($type, $interval);
  }
}

/**
 * Builds the power consumption page.
 *
 * @param $type     The sensor type.
 * @param $interval The time interval.
 * @return the power consumption page.
 */
function _logger_power_page($type, $interval) {

  $type = $type ? $type : 'electricity';
  $interval = $interval ? $interval : 'hour';

  drupal_set_title(t('Your power consumption'));

  $xvalue1 = _logger_get_xvalue(1);
  $xvalue2 = _logger_get_xvalue(2);
  $yvalue1 = _logger_get_yvalue(1);
  $yvalue2 = _logger_get_yvalue(2);
  $unit = _logger_get_unit();

  $sensors = array_merge(
    _logger_get_user_sensors($type),
    _logger_get_subscribed_sensors($type)
  );

  $chart = _logger_create_chart_object('power', $type, $interval, $unit, FALSE, $sensors, array($xvalue1, $xvalue2), array($yvalue1, $yvalue2));

  return theme('logger_power_chart_area', $chart) .

    drupal_get_form('logger_control_form', $chart);
}

/**
 * Builds the overview page.
 *
 * @param $type     The sensor type.
 * @param $interval The time interval.
 * @return the overview page.
 */
function _logger_overview_page($type, $interval) {

  $type = $type ? $type : 'electricity';
  $interval = $interval ? $interval : 'hour';

  drupal_set_title(t('Overall View'));

  $cache_id = 'logger_overview';
  $cache = cache_get($cache_id, 'cache_page');

  if ($cache->data) {
    $output = $cache->data;

  } else {

    //General explanation
    $output = theme('logger_overview_topic', NULL,
      t('<b>mySmartGrid</b> is the smart device control for your home. ' .
      'It enables you to understand your energy consumption and share your ' .
      'experiences with others.'), 'content/das-projekt');

    //Latest blogpost
    $sql = 'SELECT nid FROM {node} WHERE type = "%s" ORDER BY created DESC LIMIT 1';
    $result = db_fetch_object(db_query($sql, "blogpost"));

    if ($result) {

      $blog = node_load(array('nid' => $result->nid));

      $output .= theme('logger_overview_topic', t('Blog: ') . $blog->title, $blog->teaser, 'blog');
    }

    //Counters
    $sql = "SELECT count(*) FROM {logger_devices} d WHERE d.uid <> %d";
    $devcounter = db_result( db_query($sql, 0));

    $sql = "
      SELECT
        count(*)
      FROM
        {users} u
      WHERE
        EXISTS(
          SELECT
            1
          FROM
            {logger_devices} d
          WHERE
            d.uid = u.uid
        )";

    $usercounter = db_result( db_query($sql));

    $output .= theme('logger_overview_topic', t('Total Consumption of All Participants'),
      t('Currently, <b>@devcounter</b> Flukso devices are installed ' .
        'in <b>@usercounter</b> households. The following chart shows their ' .
        'aggregate electricity consumption.',
        array(
          '@devcounter'  => $devcounter,
          '@usercounter' => $usercounter))) . '<br>';

    cache_set($cache_id, $output, 'cache_page', time() + 1 * DAY);
  }

  $sensors = _logger_get_active_sensors($type);
  $unit = _logger_get_unit();

  $chart = _logger_create_chart_object('overview', $type, $interval, $unit, FALSE, $sensors);

  $output .= theme('logger_power_chart_area', $chart);

  return $output;
}

/**
 * Builds the relative energy consumption page.
 *
 * @return the relative energy consumption page.
 */
function _logger_relative_energy_consumption_page() {

  drupal_set_title(t('Your relative energy consumption'));

  $output = t('The following chart allows you to compare current and previous levels of
    energy consumption in six different time frames: hour, day, week, month, and year.
    The bars are explained in the legend bellow.') . '<br><br>';

  $chart = _logger_create_chart_object('relative', 'electricity', 'year', 'kWh', TRUE);

  $output .= theme('logger_energy_chart_area', $chart);

  return $output;
}

/**
 * Builds the energy consumption page.
 *
 * @return the energy consumption page.
 */
function _logger_energy_page() {

  global $user;

  $now = time();
  $start = $now - 6 * DAY - $now % DAY;
  $end = $start + 7 * DAY;
  $chart = _logger_create_chart_object('energy', 'electricity', 'week', 'kWh', FALSE, NULL, array($start, $end));

  $values = $chart->data['series'][$user->uid][$user->name][t('All')];
  $days = array_keys($values);
  $today = $days[count($days) - 1];
  $consumed = number_format($values[$today], 2, '.', ',');

  drupal_set_title(t('Your energy consumption'));

  $output = t('Today you have consumed %consumed kWh so far. ' .
    'The following chart shows your energy consumption along the week.',
    array('%consumed' => $consumed)) . '<br><br>';

  $output .= theme('logger_energy_chart_area', $chart);

  return $output;
}

/**
 * Creates an object to hold chart parameters.
 *
 * @param $context  The page where the chart is going to be placed (overview or logger).
 * @param $type     The sensor type.
 * @param $interval The time interval.
 * @param $unit     The chart unit.
 * @param $stacked  Whether the chart has stacked bars or not.
 * @param $sensors  The sensors whose values are plotted on the chart.
 * @param $xaxis    An array containing the minimum and maximum timestamps of the x axis.
 * @param $yaxis    An array containing the minimum and maximum values of the y axis.
 * @return the chart object.
 */
function _logger_create_chart_object($context, $type, $interval, $unit, $stacked, $sensors = NULL, $xaxis = array(0, 0), $yaxis = array(0, 0)) {

  $chart = new stdClass();
  $chart->context = $context;
  $chart->type = $type;
  $chart->interval = $interval;
  $chart->unit = $unit;
  $chart->stacked = $stacked;

  $chart->resolution = _logger_get_resolution($interval);
  $chart->offset = _logger_get_timezone_offset();
  $chart->colors = _logger_get_series_colors($context);
  $chart->period = _logger_get_period($interval, $chart->resolution, $xaxis[0], $xaxis[1]);
  $chart->sensors = $sensors? $sensors : _logger_get_user_sensors($type);

  if (!($xaxis[0] > 0 && $xaxis[1] > 0)) {
    $xaxis[1] = time();
    $xaxis[0] = $xaxis[1] - _logger_get_default_time_window($interval);
  }
  $chart->yaxis = $yaxis;
  $chart->xaxis = $xaxis;

  $lifetime = 15 * MINUTE;
  $t1 = $chart->period['start'] - ($chart->period['start'] % $lifetime);
  $t2 = $chart->period['end']   - ($chart->period['end']   % $lifetime);
  $unique_id = "$context $type $unit $chart->resolution $t1 $t2";
  foreach ($chart->sensors as $sensor) {
    $unique_id .= " $sensor->meter";
  }

  $chart->id = 'logger_' . $interval . '_chart_data_' . md5($unique_id);
  $cache = cache_get($chart->id, 'cache_page');
  $chart->data = $cache->data;

  if (!$chart->data) {
    $get_data = '_logger_get_' . $chart->context . '_chart_data';
    $chart->data = $get_data($chart);
    
    cache_set($chart->id, $chart->data, 'cache_page', time() + $lifetime);
  }
  return $chart;
}

/**
 * Downloads a chart data file.
 *
 * @param $cache_id  The chart cache id.
 */
function _logger_download_chart_data_file($cache_id) {

  drupal_set_header('Content-Type: text/plain');
  drupal_set_header('Content-disposition: attachment; filename=chart-data-file.txt');

  $cache = cache_get($cache_id, 'cache_page');
  if ($cache->data) {
    $header = t('Serie');
    $s = 1;

    foreach($cache->data['series'] as $uid => $userdata) {
      foreach($userdata as $username => $sensors) {
        foreach($sensors as $sensor => $measurements) {
          $header .= ',S' . $s++;

          foreach($measurements as $timestamp => $value) {
            $values[$timestamp] .= ',' . $value;
          }
        }
      }
    }

    $lines = '';
    foreach($values as $timestamp => $values_list) {
      $lines .= str_replace('<br>', ' ', $timestamp); //Removes HTML tags
      $lines .= $values_list . PHP_EOL;
    }
  }
  print $header . PHP_EOL . $lines;
  exit(0);
}

/**
 * Returns an array containing all relative energy consumption chart data.
 *
 * @return the chart data.
 */
function _logger_get_relative_chart_data($chart) {

  global $user;
  module_load_include('inc', 'logger', 'logger.rrd');

  $now = getdate();
  $extra_days['week']  = $now['wday'] - 1; //How many days since last Monday
  $extra_days['month'] = $now['mday'] - 1; //How many days since 1st day of the month
  $extra_days['year']  = $now['yday'];     //How many days since 1st day of the year

  $intervals = array(
    'hour'  => t('Hour'),
    'day'   => t('Day'),
    'week'  => t('Week'),
    'month' => t('Month'),
    'year'  => t('Year')
  );

  $legend = array(
    array('Serie' => '<b>' . t('Current')  . '</b>' . ' - ' . t('How much has been consumed so far in the current time frame.')),
    array('Serie' => '<b>' . t('Previous') . '</b>' . ' - ' . t('How much was consumed in the previous time frame.')),
    array('Serie' => '<b>' . t('Excess')   . '</b>' . ' - ' . t('How much the current consumption has exceeded the previous one.')),
  );

  foreach ($intervals as $interval => $label) {

    $resolution = _logger_get_resolution($interval);
    $adjustment = $extra_days[$interval] * DAY + ($now[0] % ($interval == 'hour' ? HOUR : DAY));

    if ($interval == 'month') {
      $last_day = getdate($now[0] - $adjustment - 12 * HOUR);
      $window = $last_day['mday'] * DAY; //Consider exactly 1 month, and not simply 30 days
    } else {
      $window = _logger_get_default_time_window($interval);
    }

    $time1 = $now[0] - $adjustment - $window;
    $time2 = $time1 + $window;

    $period1 = array('start' => $time1, 'end' => $time2 - 1); //Until the last second
    $period2 = array('start' => $time2, 'end' => $now[0] - 1);//Until the last second

    $previous = logger_rrd_query_energy($chart->sensors, 'kWh', $interval, $chart->offset, $period1, $resolution);
    $current  = logger_rrd_query_energy($chart->sensors, 'kWh', $interval, $chart->offset, $period2, $resolution);

    $perc = ($current / $previous) * 100;
    $series['current'][$label]  = $perc < 100 ? $perc       : 100;
    $series['previous'][$label] = $perc < 100?  100 - $perc :   0;
    $series['excess'][$label]   = $perc > 100?  $perc - 100 :   0;

    $data_labels['current'][$label]  = $previous * $series['current'][$label] / 100;
    $data_labels['previous'][$label] = $previous;
    $data_labels['excess'][$label]   = $previous * $perc / 100;

    $legend[0][$label] = _logger_format_period($interval, $period2, $chart->offset);
    $legend[1][$label] = _logger_format_period($interval, $period1, $chart->offset);
    $legend[2][$label] = _logger_format_period($interval, $period2, $chart->offset);
  }
  $data['series'][$user->uid][$user->name] = $series;
  $data['labels'] = $data_labels;
  $data['legend'] = $legend;

  return $data;
}

function _logger_format_period($interval, $period, $offset) {

  $start = $period['start'];
  $end = $period['end'];

  switch ($interval) {
    case 'hour':
      $start += $offset;
      $end += $offset;
      $formatted = t('from: ') . '&nbsp;' . date('H:i', $start) . '<br>' . t('to: ') . '&nbsp;&nbsp;' . date('H:i', $end);
      break;
    case 'day':
      $formatted = date('d/m', $start);
      break;
    case 'week':
      $formatted = t('from: ') . '&nbsp;' . date('d/m', $start) . '<br>' . t('to: ') . '&nbsp;&nbsp;' . date('d/m', $end);
      break;
    case 'month':
      $formatted = t(date('F', $start));
      break;
    case 'year':
      $formatted = t(date('Y', $start)) . '<br>';
      break;
  }
  return $formatted;
}

/**
 * Returns an array containing all energy consumption chart data.
 *
 * @return the chart data.
 */
function _logger_get_energy_chart_data($chart) {

  global $user;
  module_load_include('inc', 'logger', 'logger.rrd');

  $sensor = t('All');
  $min = 999999999999;
  $max = 0;
  $sum = 0;
  $total = 0;

  $from = $chart->xaxis[0];
  $to = $chart->xaxis[1] - DAY;
  for($time = $from; $time <= $to; $time += DAY) {

    $period = array('start' => $time, 'end' => ($time + DAY - 1)); //from 00:00:00 until 23:59:59
    $value = logger_rrd_query_energy($chart->sensors, 'kWh', 'day', $chart->offset, $period, $chart->resolution);

    if ($value < $min && $time < $to) {
      $min = $value;
      $min_day = $time;
    }

    if ($value > $max) {
      $max = $value;
      $max_day = $time;
    }

    $sum += $value;
    $total++;

    $title = t(date("l", $time)) . '<br>' . date("d-M", $time);
    $series[$title] = $value;

    $data_labels[$title] = $value;
  }

  $avg = $total > 0 ? $sum / $total : '';

  function _format_legend_day($value, $day) {
    return t('%value on %day', array(
      '%value' => number_format($value, 2, '.', ''),
      '%day' => t(date('l', $day))));
  }

  $line = array(
    t('User')   => $user->name,
    t('Sensor') => $sensor,
    t('Min (Except today)')    => $total > 0 ? _format_legend_day($min, $min_day) : '',
    t('Max')    => $total > 0 ? _format_legend_day($max, $max_day) : '',
    t('Avg')    => $total > 0 ? $sum / $total : '',
    t('Sum')    => $total > 0 ? $sum : ''
  );

  $data['series'][$user->uid][$user->name][$sensor] = $series;
  $data['labels'][$sensor] = $data_labels;
  $data['legend'][] = $line;

  return $data;
}

/**
 * Returns an array containing all power consumption chart data.
 * 
 * @return the chart data.
 */
function _logger_get_power_chart_data($chart) {

  module_load_include('inc', 'logger', 'logger.rrd');

  global $user;
  $i = 0;
  foreach ($chart->sensors as &$sensor) {

    $measurements = logger_rrd_query_sensor($chart->interval, $sensor, $chart->unit, $chart->offset, $chart->period, $chart->resolution);

    $values = _logger_format_power_series_data($chart, $measurements);

    $data['series'][$sensor->uid][$sensor->username][$sensor->function] = $values;

    $operations = ($sensor->uid > 0 && $sensor->uid != $user->uid)?
      '<a href="javascript: void(0)" 
        OnClick="javascript: removePowerSeries(' . "$sensor->uid, $i, '$sensor->username'" . ');">' .
        t('Remove') . '</a>' : '';

    $data['legend'][] = _logger_create_power_legend_line($sensor->username, $sensor->function, $i++, $operations);
  }
  return $data;
}

/**
 * Returns an array containing all overview chart data.
 *
 * @return the chart data.
 */
function _logger_get_overview_chart_data($chart) {

  module_load_include('inc', 'logger', 'logger.rrd');

  $measurements = logger_rrd_query_agg($chart->interval, $chart->sensors, $chart->unit, $chart->offset, $chart->period, $chart->resolution);

  $values = _logger_format_power_series_data($chart, $measurements);

  $data['series'][0][t('All')][t('All')] = $values;
  $data['legend'][] = _logger_create_power_legend_line(t('All'), t('All'), 0);

  return $data;
}

function _logger_format_power_series_data($chart, $measurements) {

  $start = $chart->period['start'] + $chart->offset - $chart->period['start'] % $chart->resolution;
  $end   = $chart->period['end']   + $chart->offset - $chart->period['end'] % $chart->resolution;

  for($timestamp = $start; $timestamp <= $end; $timestamp += $chart->resolution) {

    $key = date('Y-m-d H:i', $timestamp);
    $value = $measurements[$timestamp];

    $formatted[$key] = $value? number_format($value, 3, '.', '') : '';
  }
  return $formatted;
}

function _logger_create_power_legend_line($username, $sensor, $i, $operations = '') {

  return array(
      t('User')       => $username,
      t('Sensor')     => $sensor,
      t('Max')        => "<div id='max$i'/>",
      t('Min')        => "<div id='min$i'/>",
      t('Avg')        => "<div id='avg$i'/>",
      t('Last')       => "<div id='last$i'/>",
      t('Operation')  => $operations
  );
}

/**
 * Returns an array containing all sensors owned by the user.
 *
 * @param $type  The type of sensors to be returned.
 * @return the array of user sensors.
 */
function _logger_get_user_sensors($type) {

  global $user;

  $sql = "
    SELECT
      lm.uid,
      '%s' AS username,
      lm.meter,
      lm.function,
      lm.unit,
      lu.private
    FROM
      {logger_meters} lm
      INNER JOIN {logger_users} lu ON lm.uid = lu.uid
    WHERE
      lm.uid = %d AND
      lm.type = '%s' AND
      lm.function IS NOT NULL
    ORDER BY
      lm.function";

  $result = db_query($sql, $user->name, $user->uid, $type);

  $sensors = array();
  while ($sensor = db_fetch_object($result)) {
    $sensors[] = $sensor;
  }
  return $sensors;
}

/**
 * Returns an array containing all sensors selected to be plotted on the chart.
 *
 * @param $type  The type of sensors to be returned.
 * @return the array of user sensors.
 */
function _logger_get_subscribed_sensors($type) {

  global $user;

  if (user_access('logger')) {

    $sql = "
      SELECT
        u.uid,
        u.name AS username,
        lm.meter,
        lm.function,
        lm.unit,
        lu.private
      FROM
        ((({users} u
        INNER JOIN {user_relationships} ur ON u.uid = ur.requestee_id)
        INNER JOIN {user_relationship_types} urt ON ur.rtid = urt.rtid)
        INNER JOIN {logger_meters} lm ON u.uid = lm.uid)
        INNER JOIN {logger_users} lu ON u.uid = lu.uid
      WHERE
        ur.requester_id = %d AND
        urt.name = '%s' AND
        lm.type = '%s' AND
        lm.function IS NOT NULL
      ORDER BY
        ur.rid";

    $result = db_query($sql, $user->uid, 'subscription', $type);

    $sensors = array();
    while($sensor = db_fetch_object($result)) {
      $sensors[] = $sensor;
    }
  }
  return $sensors;
}

/**
 * Returns an array containing all active sensors.
 *
 * @param $type       The type of sensors to be returned.
 * @return the array of user sensors.
 */
function _logger_get_active_sensors($type) {

  $sql = "
    SELECT
      lm.meter
    FROM
      {logger_meters} lm
    WHERE
      lm.uid > 0 AND
      lm.type = '%s' AND
      lm.function IS NOT NULL";

  $result = db_query($sql, $type);

  $sensors = array();
  while ($sensor = db_fetch_object($result)) {

    $sensors[] = $sensor;
  }
  return $sensors;
}

/**
 * Returns an array of user devices' serial numbers indexed by their respective
 * hash codes.
 *
 * @return the array of devices.
 */
function logger_get_devices_options() {

  global $user;

  $devices = array();
  if ($user->uid) {

    $sql = "SELECT serial, device FROM {logger_devices} WHERE uid = %d ORDER BY serial";
    $result = db_query($sql, $user->uid);

    while ($row = db_fetch_array($result)) {
      $devices[$row['device']] = $row['serial'];
    }
  }
  return $devices;
}

/**
 * Returns the user timezone offset.
 *
 * @return the user timezone offset.
 */
function _logger_get_timezone_offset() {

  global $user;

  if ($user->uid) {
    $offset = $user->timezone;

  } else { //If user is not logged in

    //Gets timezone used in the browser. Auto Timezone option must be turned on.
    $offset = $_SESSION['timezone'];
  }

  return $offset;
}

function logger_theme() {

  return array(
    'logger_power_chart_area' => array(
      'arguments' => array(
        'chart' => NULL),
    ),

    'logger_energy_chart_area' => array(
      'arguments' => array(
        'chart' => NULL),
    ),

    'logger_overview_topic' => array(
      'arguments' => array(
        'title' => NULL,
        'body' => NULL,
        'link' => NULL),
    ),

    'logger_account_devices' => array(
      'arguments' => array(
        'form' => NULL),
      'file' => 'logger.admin.inc',
    ),

    'logger_account_devices_list' => array(
      'arguments' => array(
        'items' => NULL),
      'file' => 'logger.admin.inc',
    ),

    'logger_account_sensors_list' => array(
      'arguments' => array(
        'items' => NULL),
      'file' => 'logger.admin.inc',
    ),

    'logger_smoothing_level' => array(
      'arguments' => array(
        'element' => NULL),
    ),

    'logger_value_range' => array(
      'arguments' => array(
        'element' => NULL),
    ),

    'logger_time_period' => array(
      'arguments' => array(
        'element' => NULL),
    ),

    'logger_color_picker' => array(
      'arguments' => array(
        'chartId'   => NULL,
        'index'     => NULL,
        'colors'    => NULL),
    ),
  );
}

/**
 * Builds a topic of the Overview page.
 *
 * @param $title  The topic title.
 * @param $body   The topic body.
 * @param $link   The topic link.
 * @return the topic.
 */
function theme_logger_overview_topic($title, $body, $link = NULL) {

  if($title) {
    $output .= '<br><h3 class="node-headline">' . $title . '</h3>';
  }
  $output .= "<p> $body </p>";

  if($link) {
    $output .= '<p>' . l(t('read more'), $link) . '</p>';
  }
  return $output;
}

/**
 * Builds the power chart area.
 *
 * @param $chart   The power chart object.
 * @return the power chart area output.
 */
function theme_logger_power_chart_area($chart) {

  $xvalue1 = $chart->xaxis[0] * 1000;
  $xvalue2 = $chart->xaxis[1] * 1000;
  $yvalue1 = $chart->yaxis[0] + 0;
  $yvalue2 = $chart->yaxis[1] + 0;

  $chart_properties = array(
    'height'             => CHART_HEIGHT,
    'dateWindow'         => "[$xvalue1, $xvalue2]",
    'drawCallback'       => 'updateControlForm',
    'zoomCallback'       => 'updateSliderChart',
    'pointClickCallback' => 'addPowerAnnotation'
  );

  if ($yvalue1 >= 0 && $yvalue2 > 0) {
    $chart_properties['valueRange'] = "[$yvalue1, $yvalue2]";
  }

  $slider_properties = array(
    'height'           => SLIDER_HEIGHT,
    'gridLineColor'    => '"transparent"',
    'yValueFormatter'  => 'hideZero',
    'zoomCallback'     => 'updatePowerChart',
    'clickCallback'    => 'slidePowerChart',
    'underlayCallback' => 'highlightPowerChart'
  );

  $options = _logger_get_units_options();
  $unit = strtok($options[$chart->unit], ' ');

  return
    _logger_create_interval_menu($chart->context) .
    '<div>' . $unit . '</div>' .

    _logger_create_dygraph('powerChart', $chart, TRUE, $chart_properties) .
    _logger_create_dygraph('sliderChart', $chart, false, $slider_properties) .

    _logger_create_chart_legend($chart);
}

/**
 * Builds the energy consumption chart area.
 *
 * @param $chart   The energy consumption chart object.
 * @return the chart area output.
 */
function theme_logger_energy_chart_area($chart) {

  foreach ($chart->data['series'] as $uid => $userdata) {
    foreach($userdata as $username => $sensors) {
      foreach($sensors as $sensor => $values) {
        $series[] = implode(', ', $values);
      }
    }
  }
  $names = array_keys($values);

  foreach ($chart->data['labels'] as $i => $values) {
    $data_labels[] = implode(', ', $values);
  }

  $id = $chart->context . 'Chart';

  return "
    <div id='$id' style='width: 600px; height: 300px;'></div>
    <script type='text/javascript'>
      $id = createBarChart('$id',
        [ [ " . implode('], [' , $series)        . " ] ],
        ['"   . implode("', '" , $names)         . "'],
        ['"   . implode("', '" , $chart->colors) . "'],
        [ [ " . implode('], [' , $data_labels)   . " ] ], " .
        ($chart->stacked ? 'true' : 'false') . ");
    </script>" .
                
    '<br>' . t('Unit') . ': kWh' .

    '<br><br>' . _logger_create_chart_legend($chart);
}

/**
 * Creates a Dygraph chart.
 *
 * @param $id             The chart div id.
 * @param $chart          The chart object.
 * @param $create_labels  If a div needs to be created to show labels.
 * @param $properties     The Dygraph properties.
 * @return the Dygraph output.
 */
function _logger_create_dygraph($id, $chart, $create_labels, $properties) {

  $properties = array_merge($properties, array(
    'labelsDiv'         => '"chartLabels"',
    'colors'            => '["' . implode('","', $chart->colors) . '"]',
    'width'             => 600,
    'yAxisLabelWidth'   => 50,
    'axisLabelFontSize' => 12,
    'includeZero'       => 'true',
    'stepPlot'          => _logger_get_step_plot(),
    'rollPeriod'        => _logger_get_smoothing_level()
  ));

  if ($create_labels) {
    $labels_output = '<div id=' . $properties['labelsDiv'] . ' style="min-height: 20px; padding-bottom: 10px;"></div>';
  }

  foreach ($properties as $key => $value) {
    $pairs[] = "$key: $value";
  }

  return '<div id="' . $id . '"></div><br>' .
    $labels_output .
    '<script type="text/javascript">' .
        $id . ' = new Dygraph(
          document.getElementById("' . $id . '"),
          "/logger/file/' . $chart->id . '", {' .
          implode(', ', $pairs) . ' }
      );
    </script> ';
}

/**
 * Creates the chart intervals' horizontal menu.
 *
 * @param $context  The page where the menu is going to be placed (overview or logger).
 * @return the list of intervals' menus.
 */
function _logger_create_interval_menu($context) {

  $path = "$context/electricity";

  $items = array(
    l(t('Hour'),   "$path/hour"),
    l(t('Day'),    "$path/day"),
    l(t('3 Days'), "$path/days"),
    l(t('Week'),   "$path/week"),
    l(t('Month'),  "$path/month"),
    l(t('Year'),   "$path/year")
  );

  return theme_item_list($items, NULL, 'ul', array('class' => 'tabs secondary'));
}

/**
 * Builds the chart legend.
 *
 * @param $chart  The chart object.
 * @return the chart legend table.
 */
function _logger_create_chart_legend($chart) {

  $data = $chart->data['legend'];
  $header = array(
    array('data' => t('Color'))
  );

  foreach ($data as $line_id => $cells) {

    $mark = theme('logger_color_picker', $chart->context, $line_id, $chart->colors);

    $lines[$line_id] = array(
      array('data' => $mark)
    );

    foreach ($cells as $title => $value) {

      if (is_numeric($value)) {
        $value = $value > 0 ? number_format($value, 2) : '';
        $align = 'right';
      } else {
        $align = 'left';
      }

      $lines[$line_id][] = array('data' => $value, 'align' => $align);
      $header[$title] = array('data' => t($title));
    }
  }
  return theme('table', $header, $lines, array('id' => 'logger-legend-table')) .
    '<p align="right">' . l(t('Save Data'), "logger/file/" . $chart->id) . '</p>';
}

/**
 * Sets the chart series color.
 *
 * @param $chart_id  The chart id.
 * @param $i         The chart series' index.
 * @param $color     The new chart series' color.
 */
function _logger_series_color($chart_id, $i, $color) {

  global $_REQUEST;
  global $user;
  $id = SERIES_COLOR_ID . $chart_id . "_$i";

  if ($user) {
    $id .= '_' . $user->uid;
    variable_set($id, $color);

  } else {
    setcookie($id, $unit, time() + WEEK, '/');
  }
}

/**
 * Returns the list of colors used in chart series.
 *
 * @param $chart_id   The chart id.
 * @return array of colors.
 */
function _logger_get_series_colors($chart_id) {

  $palettes['energy'] = array(
    '#4D7060' //GREEN
  );
  $palettes['power'] = array(
    '#377037', //GREEN
    '#0000FC', //BLUE
    '#C11700', //RED
    '#F37E2B', //ORANGE
    '#B54FC6', //PINK
    '#809090', //GREY
    '#665C00', //BROWN
    '#050305', //BLACK
    '#0080FF', //SKYBLUE
    '#00FF00', //GREEN2
    '#00ffff', //CYAN
    '#FBEB0D', //YELLOW
    '#DED00F', //BROWN2
    '#C0C0C0'  //GRAY2
  );
  $palettes['overview'] = array(
    '#377037' //GREEN
  );
  $palettes['relative'] = array(
    '#4D7060', //GREEN4
    '#BFD9D3', //GREEN5
    '#C0C0C0'  //GRAY2
  );

  function _get_color($palette, $chart_id, $i) {

    global $user;

    $id = SERIES_COLOR_ID . $chart_id . "_$i";
    $default = $palette[$i % count($palette)];

    if ($user) {
      $id .= '_' . $user->uid;
      return variable_get($id, $default);

    } else {
      return isset($_COOKIE[$id])? $_COOKIE[$id] : $default;
    }
  }

  $palette = $palettes[$chart_id];

  for($i = 0; $i < count($palette); $i++) {
    $user_palette[$i] = _get_color($palette, $chart_id, $i);
  }
  return $user_palette;
}

function logger_block($op = 'list', $delta = 0, $edit = array()) {

  global $user;

  switch ($op) {
    case 'list':
      $blocks['posts']['info'] = t('Recent blog posts');
      $blocks['posts']['status'] = TRUE;
      $blocks['posts']['region'] = 'right';
      $blocks['posts']['weight'] = 3;
      $blocks['posts']['pages'] = '<front>\nlogger/\nlogger/*';
      $blocks['posts']['cache'] = BLOCK_CACHE_GLOBAL;
      return $blocks;

    case 'view':
      if ($delta == 'posts' && user_access('access content')) {
        $block = _logger_create_recent_blogs_block();
      }
      return $block;
  }
}

function _logger_create_recent_blogs_block() {

  $block = array();

  $sql = "
    SELECT
      n.nid,
      n.title,
      n.created
    FROM
      {node} n
    WHERE
      n.type = 'blogpost' AND
      n.status = 1
    ORDER BY
      n.created DESC";

  $result = db_query_range(db_rewrite_sql($sql), 0, 5);
  $node_title_list = node_title_list($result);

  if ($node_title_list) {
    $block['subject'] = t('Recent blog posts');
    $block['content'] = $node_title_list;
    $block['content'] .= theme('more_link', url('blog'), t('Read the latest blog entries.'));
  }
  return $block;
}

function logger_form_contact_mail_page_alter(&$form, $form_state) {

  $devices = logger_get_devices_options();
  $options = array_flip($devices);

  $form['devices'] = array(
    '#type'          => 'select',
    '#options'       => $options,
    '#default_value' => array_keys($options),
    '#multiple'      => TRUE,
    '#size'          => 1,
    '#attributes'    => array('style' => 'visibility:hidden;'),
  );
}

function logger_mail_alter(&$message) {

  switch($message['id']) {

    case 'contact_page_mail':
      $devices = $message['params']['devices'];

      if (count($devices) > 0) {
        $message['body'][] = t("User Devices: ") . implode(', ', $devices);
      }
    break;
  }
}

function logger_control_form(&$form_state, $chart) {

  global $base_path;

  $form['new_user'] = array(
    '#type'           => 'select',
    '#title'          => t('Add User'),
    '#description'    => t('Select a user to be added to the chart.'),
    '#options'        => _logger_get_users_options(),
    '#default_value'  => 0,
    '#attributes'     => array('onchange' => 'submitControlForm(true)')
  );

  $form['unit'] = array(
    '#type'           => 'select',
    '#title'          => t('Chart Unit'),
    '#description'    => t('Select the chart unit.'),
    '#options'        => _logger_get_units_options(),
    '#default_value'  => _logger_get_unit(),
    '#required'       => TRUE,
    '#attributes'     => array('onchange' => 'submitControlForm(true)')
  );

  $form['step_plot'] = array(
    '#type'           => 'checkbox',
    '#title'          => t('Stepped Lines'),
    '#description'    => t('Do you want the chart series to use stepped lines?'),
    '#default_value'  => _logger_get_step_plot(),
    '#return_value'   => 1,
    '#required'       => TRUE,
    '#attributes'     => array('onchange' => 'submitControlForm()')
  );

  $form['smoothing_level'] = array(
    '#type'           => 'textfield',
    '#theme'          => 'logger_smoothing_level',
    '#title'          => t('Smoothing Level'),
    '#description'    => t("Increase this number to smooth the series' lines and make the chart more readable."),
    '#maxlength'      => 5,
    '#size'           => 5,
    '#text-align'     => 'center',
    '#default_value'  => _logger_get_smoothing_level(),
    '#required'       => TRUE
  );

  $form['yvalue'] = array(
    '#type'           => 'textfield',
    '#theme'          => 'logger_value_range',
    '#title'          => t('Value Range'),
    '#description'    => t("Enter the value range shown on the Y axis, and click the Refresh button."),
    '#maxlength'      => 12,
    '#size'           => 12,
    '#text-align'     => 'right'
  );

  $form['xvalue'] = array(
    '#type'           => 'textfield',
    '#theme'          => 'logger_time_period',
    '#title'          => t('Time Period'),
    '#description'    => t("Enter the time period shown on the X axis, and click the Refresh button."),
    '#text-align'     => 'center'
  );

  $form['resolution'] = array(
    '#type'           => 'select',
    '#title'          => t('Time Resolution'),
    '#description'    => t('Select the amount of time represented by each point on the chart.'),
    '#options'        => _logger_get_resolutions_options(),
    '#attributes'     => array('onchange' => 'submitControlForm()')
  );

  $form['submit'] = array(
    '#type'   => 'submit',
    '#value'  => t('Refresh')
  );

  return $form;
}

/**
 * Builds the Smoothing Level field.
 *
 * @param $element  The Drupal form field element.
 * @return the field HTML code.
 */
function theme_logger_smoothing_level($element) {

  function _operation_button($field_id, $caption, $step) {
    return '<input type="button" value="' . $caption . '" '.
      'onClick="javascript: return updateSmoothingLevel(' . "'$field_id', " . $step . ');"/>';
  }

  $id = $element['#id'];
  $value = check_plain($element['#value']);

  $output =
    _operation_button($id, '<<', -10) .
    _operation_button($id, '<',  -1) .

    _logger_create_custom_field($element, '', $value, $attributes) .

    _operation_button($id, '>',   1) .
    _operation_button($id, '>>',  10);

  return theme('form_element', $element, $output);
}

/**
 * Builds the group of fields for informing value range.
 *
 * @param $element  The Drupal form field element.
 * @return the field HTML code.
 */
function theme_logger_value_range($element) {

  $field1 = _logger_create_custom_field($element, 1, '');
  $field2 = _logger_create_custom_field($element, 2, '');

  return _logger_compose_range_fields($element, $field1, $field2);
}

/**
 * Builds the group of fields for informing a time period.
 *
 * @param $element  The Drupal form field element.
 * @return the field HTML code.
 */
function theme_logger_time_period($element) {

  $field1 = _logger_create_time_fields($element, 1);
  $field2 = _logger_create_time_fields($element, 2);

  return _logger_compose_range_fields($element, $field1, $field2);
}

/**
 * Builds a color picker component.
 *
 * @param $i          The color index.
 * @param $colors     The array of colors.
 * @param $picker_id  The picker id.
 * @return the picker HTML code.
 */
function theme_logger_color_picker($chart_id, $i, $colors) {

  $id = SERIES_COLOR_ID . $i;

  return '
    <input
      class="color {valueElement:' . "'$id'" . '}
      type="button"
      style="width: 10px; height: 10px; color: transparent;"/>

    <input
      id="' . $id . '"
      type="hidden"
      value="' . $colors[$i % count($colors)] . '"
      onchange="javascript: ' . "setSeriesColor('$chart_id', $i, this.value)" . ';"/>';
}

/**
 * Creates two fields to represent a timestamp: one for date and another for time.
 *
 * @param $element  The Drupal form field element.
 * @param $sufix    A sufix for the field id and name.
 * @return the fields HTML code.
 */
function _logger_create_time_fields($element, $sufix) {

  $picker_properties = "{
      yearRange: '-1:+0',
      showAnim: 'fadeIn',
      dateFormat: 'dd/mm/yy',
      currentText: '" . t('Today') . "',
      nextText: '" . t('Next Month') . "',
      prevText: '" . t('Previous Month') . "',
      dayNamesMin: [" . t("'Su','Mo','Tu','We','Th','Fr','Sa'") . "],
      monthNames: ['" . t('January') . "', '" . t('February') . "', '" . t('March') . "', '" . t('April') . "', '" . t('May') . "', '" . t('June') . "', '" . t('July') . "', '" . t('August') . "', '" . t('September') . "', '" . t('October') . "', '" . t('November') . "', '" . t('December') . "']
    }";

  drupal_add_js('$(document).ready(function(){$("#edit-xvalue' . $sufix . 'date").datepicker('. $picker_properties .');});', 'inline');

  return
    _logger_create_custom_field($element, $sufix . 'date', '', 10, 10) .
    _logger_create_custom_field($element, $sufix . 'time', '', 5, 5);
}

/**
 * Arrange fields to represent a range.
 *
 * @param $element  The Drupal form field element.
 * @param $field1   The field that contains the lowest value.
 * @param $field2   The field that contains the highest value.
 * @return the fields HTML code.
 */
function _logger_compose_range_fields($element, $field1, $field2) {

  $output = t('from: ') . $field1 . ' &nbsp;&nbsp;&nbsp;' . t('to: ') . $field2;
  return theme('form_element', $element, $output);
}

/**
 * Create a customized form field.
 *
 * @param $element     The Drupal form field element.
 * @param $sufix       A sufix for the field id and name.
 * @param $value       The field value.
 * @param $size        The field size.
 * @param $maxlength   The field maximum length.
 * @return the field HTML code.
 */
function _logger_create_custom_field($element, $sufix, $value, $size = 0, $maxlength = 0) {

  $name      = $element['#name'] . $sufix;
  $id        = $element['#id']   . $sufix;
  $align     = $element['#text-align'] . ';';
  $size      = $size > 0 ? $size : $element['#size'];
  $maxlength = $maxlength > 0 ? $maxlength : $element['#maxlength'];

  $attributes = isset($element['#attributes']) ? drupal_attributes($element['#attributes']) : '';

  return
    '<input type="text" ' .
    'name="'              . $name      . '" ' .
    'id="'                . $id        . '" ' .
    'maxlength="'         . $maxlength . '" ' .
    'size="'              . $size      . '" ' .
    'value="'             . $value     . '" ' .
    'style="text-align: ' . $align     . '" ' .
    $attributes . ' />';
}

function logger_control_form_validate($form, &$form_state) {

  $smoothing_level = $form_state['values']['smoothing_level'];

  if ($smoothing_level < 1) {
    form_set_error('smoothing_level', t('The smoothing level must be greater than 0.'));
  }

  $step_plot = $form_state['values']['step_plot'];

  if ($step_plot != 1 && $step_plot != 0) {
    form_set_error('step_plot', t('The stepped lines option must be either 0 or 1.'));
  }

  $yvalue1 = _logger_get_yvalue(1);
  $yvalue2 = _logger_get_yvalue(2);

  if (!($yvalue1 == '' && $yvalue2 == '') && !($yvalue1 >= 0 && $yvalue2 > $yvalue1)) {

    form_set_error('yvalue', t('The value range is invalid.'));
  }

  $xvalue1 = _logger_get_xvalue(1);
  $xvalue2 = _logger_get_xvalue(2);

  if (!($xvalue1 > 0 && $xvalue2 > 0 && $xvalue2 > $xvalue1)) {

    form_set_error('xvalue', t('Time period is invalid.'));
  }
}

function logger_control_form_submit($form, &$form_state) {

  global $_REQUEST;

  $new_user        = $form_state['values']['new_user'];
  $unit            = $form_state['values']['unit'];
  $step_plot       = $form_state['values']['step_plot'];
  $smoothing_level = $form_state['values']['smoothing_level'];

  if ($new_user > 0) {
    _logger_add_user($new_user);
  }

  _logger_set_unit($unit);
  _logger_set_step_plot($step_plot);
  _logger_set_smoothing_level($smoothing_level);

  $form_state['redirect'] = array($_GET['q'], $_REQUEST);
}

/**
 * Returns an array of units indexed by their respective acronym.
 *
 * @return the array of units.
 */
function _logger_get_units_options() {

  return array(
    'watt' => t('watt'),
    'kwh'  => t('kWh/year'),
    'eur'  => t('euro/year (0.18eur/kWh)'),
    'aud'  => t('aud/year (0.19aud/kWh)')
  );
}

/**
 * Sets the chart unit.
 *
 * @param $unit  The new unit.
 */
function _logger_set_unit($unit) {

  global $user;
  $id = CHART_UNIT_ID;

  if ($user) {
    $id .= $user->uid;
    variable_set($id, $unit);

  } else {
    setcookie($id, $unit, time() + WEEK, '/');
  }
}

/**
 * Returns the chart unit.
 *
 * @return the chart unit.
 */
function _logger_get_unit() {

  global $user;
  $id = CHART_UNIT_ID;

  if ($user) {
    $id .= $user->uid;
    $unit = variable_get($id, 'watt');

  } else {
    $unit = isset($_COOKIE[$id])? $_COOKIE[$id] : 'watt';
  }
  return $unit;
}

/**
 * Sets the chart smooting level.
 *
 * @param $level  The new smooting level.
 */
function _logger_set_smoothing_level($level) {

  global $user;
  $id = SMOOTHING_LEVEL_ID . $user->uid;

  variable_set($id, $level);
}

/**
 * Returns the chart smooting level.
 *
 * @return The chart smooting level.
 */
function _logger_get_smoothing_level() {

  global $user;

  if ($user) {
    $id = SMOOTHING_LEVEL_ID . $user->uid;
    $level = variable_get($id, 1);

  } else {
    $level = 1;
  }
  return $level;
}

/**
 * Returns whether the chart is stepped or not.
 *
 * @return 1 if it is, 0 otherwise.
 */
function _logger_get_step_plot() {

  global $user;

  if ($user) {
    $id = STEP_PLOT_ID . $user->uid;
    $step_plot = variable_get($id, 0);

  } else {
    $step_plot = 0;
  }
  return $step_plot;
}

/**
 * Sets  whether the chart is stepped or not.
 *
 * @param $step_plot  1 if it is, 0 otherwise.
 */
function _logger_set_step_plot($step_plot) {

  global $user;
  $id = STEP_PLOT_ID . $user->uid;

  variable_set($id, $step_plot);
}

/**
 * Returns either the lowest or the highest value shown on the Y axis.
 *
 * @param $index Inform 1 for the lowest, 2 for the highest.
 *
 * @return the value.
 */
function _logger_get_yvalue($index) {
  return $_REQUEST['yvalue' . $index];
}

/**
 * Returns either the lowest or the highest value shown on the X axis.
 *
 * @param $index Inform 1 for the lowest, 2 for the highest.
 *
 * @return the value.
 */
function _logger_get_xvalue($index) {

  $formatted = $_REQUEST['xvalue' . $index. 'date'] . ' ' . $_REQUEST['xvalue' . $index. 'time'];

  //Parses a datetime string formatted as dd/mm/yyyy hh:mm to a Unix timestamp.
  $str = "$formatted:00 GMT+00:00";
  $d = strtok($str, '/');
  $m = strtok('/');
  $r = strtok('/');
  $timestamp = strtotime("$m/$d/$r");
  $timestamp -= _logger_get_timezone_offset();

  return $timestamp > 0 ? $timestamp : 0;
}

/**
 * Returns the chart resolution of a time interval menu option.
 *
 * @param $interval  The time interval menu option.
 * @return the chart resolution.
 */
function _logger_get_resolution($interval) {

  $resolution = $_REQUEST['resolution'];
  if ($resolution > 0) {
    return $resolution;
  }

  $options = array(
    'hour'  =>  1 * MINUTE,
    'day'   => 15 * MINUTE,
    'days'  => 15 * MINUTE,
    'week'  => 15 * MINUTE,
    'month' =>  1 * DAY,
    'year'  =>  1 * WEEK
  );

  return $options[$interval];
}

/**
 * Returns an array of chart resolutions.
 *
 * @return the array of chart resolutions.
 */
function _logger_get_resolutions_options() {

  return array(
     1 * MINUTE =>  1 . ' ' . t('Minute'),
    15 * MINUTE => 15 . ' ' . t('Minutes'),
     1 * DAY    =>  1 . ' ' . t('Day'),
     1 * WEEK   =>  1 . ' ' . t('Week')
  );
}

/**
 * Returns the default time window associated with a time interval menu option.
 *
 * @param $interval  The time interval menu option.
 * @return the amount of seconds of the time window.
 */
function _logger_get_default_time_window($interval) {

  $windows = array(
    'hour'  =>   1 * HOUR,
    'day'   =>   1 * DAY,
    'days'  =>   3 * DAY,
    'week'  =>   7 * DAY,
    'month' =>  30 * DAY,
    'year'  => 365 * DAY
  );
  return $windows[$interval];
}

/**
 * Returns an array containing two timestamps representing a period of time.
 *
 * @param $interval    The time interval menu option.
 * @param $resolution  The time resolution.
 * @param $start       The initial timestamp, if known.
 * @param $end         The final timestamp, if known.
 * @return the period of time as an array.
 */
function _logger_get_period($interval, $resolution, $start = 0, $end = 0) {

  module_load_include('inc', 'logger', 'logger.rrd');
  $now = time();

  if ($start > 0 && $end > 0) {
    $window = $end - $start;

  } else {
    $window = _logger_get_default_time_window($interval);
    $end = $now;
  }

  $storage_periods = logger_get_storage_periods();
  $elapsed_time = $now - $end;
  $max_window = $storage_periods[$resolution] - $elapsed_time;

  $window *= (CHART_HEIGHT / SLIDER_HEIGHT);
  $window = $window > $max_window ? $max_window : $window;

  $start = $end - $window;

  return array('start' => $start, 'end'   => $end);
}

/**
 * Returns an array of fluksonian users indexed by their respective user id.
 * Only users not yet plotted on the chart are returned.
 *
 * @return the array of fluksonian users.
 */
function _logger_get_users_options() {

  global $user;

  $sql = "
    SELECT
      f.uid,
      f.name
    FROM
      {users} f,
      {users_roles} ur,
      {role} r
    WHERE
      f.uid <> %d AND
      f.uid = ur.uid AND
      ur.rid = r.rid AND
      r.name = '%s' AND
      NOT EXISTS(
        SELECT
          1
        FROM
          {user_relationships} urel,
          {user_relationship_types} t
        WHERE
          t.name = '%s' AND
          urel.rtid = t.rtid AND
          urel.requestee_id = f.uid AND
          urel.requester_id = %d
      )
    ORDER BY
      f.name";

  $fluksonians = db_query($sql, $user->uid, 'fluksonian', 'subscription', $user->uid);

  $options = array(0 => '');
  while($fluksonian = db_fetch_object($fluksonians)) {
    $options[$fluksonian->uid] = $fluksonian->name;
  }
  return $options;
}

/**
 * Adds an user to the chart.
 *
 * @param $uid  The id of the user to be added.
 */
function _logger_add_user($uid) {

  global $user;

  // don't allow users to add themselves
  if ($uid != $user->uid) {

    $sql = "SELECT rtid FROM {user_relationship_types} WHERE name = '%s'";
    $rtid = db_result(db_query($sql, 'subscription'));

    user_relationships_request_relationship($user->uid, $uid, $rtid, TRUE);
  }
}

/**
 * Removes an user from the chart.
 *
 * @param $requestee_id  The id of the user to be removed.
 */
function _logger_remove_user($requestee_id) {

  global $user;

  $sql = "
    DELETE
      FROM {user_relationships}
    WHERE
      requester_id = %d AND
      requestee_id = %d";

  db_query($sql, $user->uid, $requestee_id);
}

function logger_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'user_login') {
    $form['#redirect'] = 'logger';
    $form['name']['#size'] = 20;
    $form['pass']['#size'] = 20;
  }
}

/**
 * Access callback ensuring the user account tabs are visible only to the owner.
 *
 * @param $permission Required permission to view the item.
 * @param $account    A user object.
 */
function _logger_account_access($permission, $account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access($permission));
}

/**
 * Access callback ensuring the sensor is accessible only to the owner.
 */
function _logger_sensor_access($permission, $meter) {

  $sql = "SELECT uid FROM {logger_meters} WHERE meter = '%s'";
  $sensor = db_fetch_object(db_query($sql, $meter));

  return ($sensor->uid == $GLOBALS['user']->uid && user_access($permission));
}

/**
 * Access callback ensuring the device is accessible only to the owner.
 */
function _logger_device_access($permission, $serial) {

  $sql = "SELECT uid FROM {logger_devices} WHERE serial = %d";
  $device = db_fetch_object(db_query($sql, $serial));

  return ($device->uid == $GLOBALS['user']->uid && user_access($permission));
}

/**
 * Queries the databases for measurements reported by sensors of a single device.
 *
 * @param $interval The time interval.
 * @param $device   The device's hash code.
 * @param $offset   The user timezone offset.
 * @return the array of sensors' measurements, formatted as [meter][function][ [timestamp, value] ].
 */
function logger_query_device_measurements($interval, $device, $offset) {

  module_load_include('inc', 'logger', 'logger.rrd');

  $sql = "SELECT m.meter, m.function FROM {logger_meters} m WHERE m.device = '%s'";
  $sensors = db_query($sql, $device);
  $measurements = array();

  $resolution = _logger_get_resolution($interval);
  $period = _logger_get_period($interval, $resolution);

  while($sensor = db_fetch_object($sensors)) {

    $measurements[$sensor->meter][$sensor->function] = logger_rrd_query_sensor($interval, $sensor, 'watt', $offset, $period, $resolution);
  }
  return $measurements;
}
